---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
  labels:
    # ldpreload-related labels
    ldpreload: "true"

spec:
  restartPolicy: Never

  containers:
    - name: nginx-proxy
      image: nginx-proxy
      imagePullPolicy: IfNotPresent
      env:
        # ldpreload-related env vars
        - name: VCL_APP_SCOPE_GLOBAL
          value: ""
        - name: VCL_APP_SCOPE_LOCAL
          value: ""
        - name: VCL_APP_PROXY_TRANSPORT_TCP
          value: ""
        # enable verbose VCL debugs, do not use for production
        - name: VCL_DEBUG
          value: "3"

    - name: nginx-server
      image: nginx
      imagePullPolicy: IfNotPresent
      env:
        # ldpreload-related env vars
        - name: VCL_APP_SCOPE_LOCAL
          value: ""
        # enable verbose VCL debugs, do not use for production
        - name: VCL_DEBUG
          value: "3"
