#!/bin/sh

if [ $DEP_SCENARIO = "nostn" ]; then

  master_gw_config='\
    NodeConfig:\
    - NodeName: \"k8s-master\"\
      MainVppInterface:\
        InterfaceName: \"GigabitEthernet0/8/0\"\
      Gateway: \"10.1.253.254\"'

  worker_gw_config=''
for i in `seq 1 $NUM_K8S_NODES`; do
worker_gw_config=$worker_gw_config'\
    - NodeName: \"k8s-worker'$i'\"\
      MainVppInterface:\
        InterfaceName: \"GigabitEthernet0/8/0\"\
      Gateway: \"10.1.253.254\"'
done

  sed -i "/logs.conf/i \
""${master_gw_config}""\
""${worker_gw_config}""\
" /home/vagrant/gopath/src/github.com/contiv/vpp/k8s/contiv-vpp/manifest.yaml

else
  curl -s https://raw.githubusercontent.com/contiv/vpp/master/k8s/stn-install.sh > /tmp/contiv-stn.sh
  chmod +x /tmp/contiv-stn.sh
  sudo /tmp/contiv-stn.sh

  sed -i '/NatExternalTraffic/a\
    StealInterface: "enp0s8"' /home/vagrant/gopath/src/github.com/contiv/vpp/k8s/contiv-vpp/manifest.yaml
fi
