// Code generated by protoc-gen-go. DO NOT EDIT.
// source: container.proto

/*
Package container is a generated protocol buffer package.

It is generated from these files:
	container.proto

It has these top-level messages:
	Persisted
*/
package container

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Persisted represents configured items for a pod that are persisted.
type Persisted struct {
	// id is identifier of pod
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	// podName
	PodName      string `protobuf:"bytes,2,opt,name=podName" json:"podName,omitempty"`
	PodNamespace string `protobuf:"bytes,3,opt,name=podNamespace" json:"podNamespace,omitempty"`
	// Veth1 is name of one end end of veth pair that is in the given container namespace.
	// Nil if TAPs are used instead.
	Veth1Name string `protobuf:"bytes,4,opt,name=Veth1Name" json:"Veth1Name,omitempty"`
	// Veth2 is name the other end of veth pair in the default namespace
	// Nil if TAPs are used instead.
	Veth2Name string `protobuf:"bytes,5,opt,name=Veth2Name" json:"Veth2Name,omitempty"`
	// VppIf is name AF_PACKET/TAP interface connecting pod to VPP
	VppIfName string `protobuf:"bytes,6,opt,name=VppIfName" json:"VppIfName,omitempty"`
	// PodTap is name ofthe host end of the tap connecting pod to VPP
	// Nil if TAPs are not used
	PodTapName string `protobuf:"bytes,7,opt,name=PodTapName" json:"PodTapName,omitempty"`
	// Loopback is interface name associated with the pod.
	// Nil if VPP TCP stack is disabled.
	LoopbackName string `protobuf:"bytes,8,opt,name=LoopbackName" json:"LoopbackName,omitempty"`
	// StnRule is name of STN rule used to "punt" any traffic via VETHs/TAPs with no match in VPP TCP stack.
	// Nil if VPP TCP stack is disabled.
	StnRuleName string `protobuf:"bytes,9,opt,name=StnRuleName" json:"StnRuleName,omitempty"`
	// AppNamespace is id of the application namespace associated with the pod.
	// Nil if VPP TCP stack is disabled.
	AppNamespaceID string `protobuf:"bytes,10,opt,name=AppNamespaceID" json:"AppNamespaceID,omitempty"`
	// VppARPEntryInterface is name of the Interface associated ARP entry configured in VPP to route traffic from VPP to pod.
	VppARPEntryInterface string `protobuf:"bytes,11,opt,name=VppARPEntryInterface" json:"VppARPEntryInterface,omitempty"`
	// VppARPEntryIP is IP associated ARP entry configured in VPP to route traffic from VPP to pod.
	VppARPEntryIP string `protobuf:"bytes,12,opt,name=VppARPEntryIP" json:"VppARPEntryIP,omitempty"`
	// PodARPEntry is name of ARP entry configured in the pod to route traffic from pod to VPP.
	PodARPEntryName string `protobuf:"bytes,13,opt,name=PodARPEntryName" json:"PodARPEntryName,omitempty"`
	// VppRouteVrf is vrf of the route from VPP to the container
	VppRouteVrf uint32 `protobuf:"varint,15,opt,name=VppRouteVrf" json:"VppRouteVrf,omitempty"`
	// VppRouteDest is destination of the route from VPP to the container
	VppRouteDest string `protobuf:"bytes,16,opt,name=VppRouteDest" json:"VppRouteDest,omitempty"`
	// VppRouteNextHop is next hop of the route from VPP to the container
	VppRouteNextHop string `protobuf:"bytes,17,opt,name=VppRouteNextHop" json:"VppRouteNextHop,omitempty"`
	// PodLinkRoute is name of the route from pod to the default gateway.
	PodLinkRouteName string `protobuf:"bytes,18,opt,name=PodLinkRouteName" json:"PodLinkRouteName,omitempty"`
	// PodDefaultRoute is name of the default gateway for the pod.
	PodDefaultRouteName string `protobuf:"bytes,19,opt,name=PodDefaultRouteName" json:"PodDefaultRouteName,omitempty"`
}

func (m *Persisted) Reset()                    { *m = Persisted{} }
func (m *Persisted) String() string            { return proto.CompactTextString(m) }
func (*Persisted) ProtoMessage()               {}
func (*Persisted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Persisted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Persisted) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *Persisted) GetPodNamespace() string {
	if m != nil {
		return m.PodNamespace
	}
	return ""
}

func (m *Persisted) GetVeth1Name() string {
	if m != nil {
		return m.Veth1Name
	}
	return ""
}

func (m *Persisted) GetVeth2Name() string {
	if m != nil {
		return m.Veth2Name
	}
	return ""
}

func (m *Persisted) GetVppIfName() string {
	if m != nil {
		return m.VppIfName
	}
	return ""
}

func (m *Persisted) GetPodTapName() string {
	if m != nil {
		return m.PodTapName
	}
	return ""
}

func (m *Persisted) GetLoopbackName() string {
	if m != nil {
		return m.LoopbackName
	}
	return ""
}

func (m *Persisted) GetStnRuleName() string {
	if m != nil {
		return m.StnRuleName
	}
	return ""
}

func (m *Persisted) GetAppNamespaceID() string {
	if m != nil {
		return m.AppNamespaceID
	}
	return ""
}

func (m *Persisted) GetVppARPEntryInterface() string {
	if m != nil {
		return m.VppARPEntryInterface
	}
	return ""
}

func (m *Persisted) GetVppARPEntryIP() string {
	if m != nil {
		return m.VppARPEntryIP
	}
	return ""
}

func (m *Persisted) GetPodARPEntryName() string {
	if m != nil {
		return m.PodARPEntryName
	}
	return ""
}

func (m *Persisted) GetVppRouteVrf() uint32 {
	if m != nil {
		return m.VppRouteVrf
	}
	return 0
}

func (m *Persisted) GetVppRouteDest() string {
	if m != nil {
		return m.VppRouteDest
	}
	return ""
}

func (m *Persisted) GetVppRouteNextHop() string {
	if m != nil {
		return m.VppRouteNextHop
	}
	return ""
}

func (m *Persisted) GetPodLinkRouteName() string {
	if m != nil {
		return m.PodLinkRouteName
	}
	return ""
}

func (m *Persisted) GetPodDefaultRouteName() string {
	if m != nil {
		return m.PodDefaultRouteName
	}
	return ""
}

func init() {
	proto.RegisterType((*Persisted)(nil), "container.Persisted")
}

func init() { proto.RegisterFile("container.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdd, 0x6a, 0xf2, 0x40,
	0x10, 0x40, 0xd1, 0xef, 0x53, 0x9b, 0xf1, 0xb7, 0x63, 0x2f, 0xf6, 0xa2, 0x14, 0x91, 0x52, 0xa4,
	0x17, 0xa5, 0xb5, 0x4f, 0x20, 0xa4, 0xd0, 0x80, 0xc8, 0x92, 0x96, 0xdc, 0x47, 0xb3, 0xa1, 0xa2,
	0xcd, 0x0e, 0xc9, 0x0a, 0xed, 0x73, 0xf4, 0x85, 0x4b, 0x26, 0x46, 0xd7, 0xd4, 0x3b, 0xf7, 0x9c,
	0x23, 0x3b, 0x3b, 0x04, 0xfa, 0x2b, 0x9d, 0x98, 0x70, 0x9d, 0xa8, 0xf4, 0x81, 0x52, 0x6d, 0x34,
	0x3a, 0x07, 0x30, 0xfe, 0x69, 0x80, 0x23, 0x55, 0x9a, 0xad, 0x33, 0xa3, 0x22, 0xec, 0x41, 0xdd,
	0x73, 0x45, 0x6d, 0x54, 0x9b, 0x38, 0x7e, 0xdd, 0x73, 0x51, 0x40, 0x8b, 0x74, 0xb4, 0x08, 0x3f,
	0x95, 0xa8, 0x33, 0x2c, 0x8f, 0x38, 0x86, 0xce, 0xfe, 0x67, 0x46, 0xe1, 0x4a, 0x89, 0x7f, 0xac,
	0x4f, 0x18, 0x5e, 0x83, 0x13, 0x28, 0xf3, 0xf1, 0xc4, 0xff, 0xff, 0xcf, 0xc1, 0x11, 0x94, 0x76,
	0xca, 0xb6, 0x71, 0xb4, 0xd3, 0x83, 0x25, 0xf2, 0x62, 0xb6, 0xcd, 0xbd, 0x2d, 0x01, 0xde, 0x00,
	0x48, 0x1d, 0xbd, 0x87, 0xc4, 0xba, 0xc5, 0xda, 0x22, 0xf9, 0x74, 0x73, 0xad, 0x69, 0x19, 0xae,
	0x36, 0x5c, 0x5c, 0x14, 0xd3, 0xd9, 0x0c, 0x47, 0xd0, 0x7e, 0x33, 0x89, 0xbf, 0xdb, 0x2a, 0x4e,
	0x1c, 0x4e, 0x6c, 0x84, 0x77, 0xd0, 0x9b, 0x11, 0x1d, 0xde, 0xe3, 0xb9, 0x02, 0x38, 0xaa, 0x50,
	0x9c, 0xc2, 0x55, 0x40, 0x34, 0xf3, 0xe5, 0x4b, 0x62, 0xd2, 0x6f, 0x2f, 0x31, 0x2a, 0x8d, 0xf3,
	0x9d, 0xb4, 0xb9, 0x3e, 0xeb, 0xf0, 0x16, 0xba, 0x36, 0x97, 0xa2, 0xc3, 0xf1, 0x29, 0xc4, 0x09,
	0xf4, 0xa5, 0x8e, 0x4a, 0xc0, 0x73, 0x76, 0xb9, 0xab, 0xe2, 0xfc, 0x35, 0x01, 0x91, 0xaf, 0x77,
	0x46, 0x05, 0x69, 0x2c, 0xfa, 0xa3, 0xda, 0xa4, 0xeb, 0xdb, 0x28, 0xdf, 0x49, 0x79, 0x74, 0x55,
	0x66, 0xc4, 0xa0, 0xd8, 0x89, 0xcd, 0xf2, 0xfb, 0xca, 0xf3, 0x42, 0x7d, 0x99, 0x57, 0x4d, 0xe2,
	0xb2, 0xb8, 0xaf, 0x82, 0xf1, 0x1e, 0x06, 0x52, 0x47, 0xf3, 0x75, 0xb2, 0x29, 0x70, 0x3e, 0x1a,
	0x72, 0xfa, 0x87, 0xe3, 0x23, 0x0c, 0xa5, 0x8e, 0x5c, 0x15, 0x87, 0xbb, 0xad, 0x39, 0xe6, 0x43,
	0xce, 0xcf, 0xa9, 0x65, 0x93, 0xbf, 0xd3, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xfe,
	0xad, 0xb5, 0xba, 0x02, 0x00, 0x00,
}
