// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: container.proto

package container

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Persisted represents configured items for a pod that are persisted.
type Persisted struct {
	// id is identifier of pod
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// podName
	PodName      string `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	PodNamespace string `protobuf:"bytes,3,opt,name=podNamespace,proto3" json:"podNamespace,omitempty"`
	// Veth1 is name of one end end of veth pair that is in the given container namespace.
	// Nil if TAPs are used instead.
	Veth1Name string `protobuf:"bytes,4,opt,name=Veth1Name,proto3" json:"Veth1Name,omitempty"`
	// Veth2 is name the other end of veth pair in the default namespace
	// Nil if TAPs are used instead.
	Veth2Name string `protobuf:"bytes,5,opt,name=Veth2Name,proto3" json:"Veth2Name,omitempty"`
	// VppIf is name AF_PACKET/TAP interface connecting pod to VPP
	VppIfName string `protobuf:"bytes,6,opt,name=VppIfName,proto3" json:"VppIfName,omitempty"`
	// PodTap is name ofthe host end of the tap connecting pod to VPP
	// Nil if TAPs are not used
	PodTapName string `protobuf:"bytes,7,opt,name=PodTapName,proto3" json:"PodTapName,omitempty"`
	// VppARPEntryInterface is name of the Interface associated with ARP entry configured in VPP to route traffic from VPP to pod.
	VppARPEntryInterface string `protobuf:"bytes,11,opt,name=VppARPEntryInterface,proto3" json:"VppARPEntryInterface,omitempty"`
	// VppARPEntryIP is IP associated with ARP entry configured in VPP to route traffic from VPP to pod.
	VppARPEntryIP string `protobuf:"bytes,12,opt,name=VppARPEntryIP,proto3" json:"VppARPEntryIP,omitempty"`
	// PodARPEntryInterface is name of the Interface associated with ARP entry configured in Linux to route traffic from pod to VPP.
	PodARPEntryInterface string `protobuf:"bytes,13,opt,name=PodARPEntryInterface,proto3" json:"PodARPEntryInterface,omitempty"`
	// PodARPEntryIP is IP associated with ARP entry configured in Linux to route traffic from pod to VPP.
	PodARPEntryIP string `protobuf:"bytes,14,opt,name=PodARPEntryIP,proto3" json:"PodARPEntryIP,omitempty"`
	// VppRouteVrf is vrf of the route from VPP to the container
	VppRouteVrf uint32 `protobuf:"varint,15,opt,name=VppRouteVrf,proto3" json:"VppRouteVrf,omitempty"`
	// VppRouteDest is destination of the route from VPP to the container
	VppRouteDest string `protobuf:"bytes,16,opt,name=VppRouteDest,proto3" json:"VppRouteDest,omitempty"`
	// VppRouteNextHop is next hop of the route from VPP to the container
	VppRouteNextHop string `protobuf:"bytes,17,opt,name=VppRouteNextHop,proto3" json:"VppRouteNextHop,omitempty"`
	// PodLinkRouteDest is destination of the route from container to default GW.
	PodLinkRouteDest string `protobuf:"bytes,18,opt,name=PodLinkRouteDest,proto3" json:"PodLinkRouteDest,omitempty"`
	// PodLinkRouteNextHop is the name of the outgoing interface for the route from container to default GW.
	PodLinkRouteInterface string `protobuf:"bytes,19,opt,name=PodLinkRouteInterface,proto3" json:"PodLinkRouteInterface,omitempty"`
	// PodDefaultRouteInterface is the name of the outgoing interface for pod's default route.
	PodDefaultRouteInterface string   `protobuf:"bytes,20,opt,name=PodDefaultRouteInterface,proto3" json:"PodDefaultRouteInterface,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Persisted) Reset()         { *m = Persisted{} }
func (m *Persisted) String() string { return proto.CompactTextString(m) }
func (*Persisted) ProtoMessage()    {}
func (*Persisted) Descriptor() ([]byte, []int) {
	return fileDescriptor_container_0c4ce2710ed9398e, []int{0}
}
func (m *Persisted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persisted.Unmarshal(m, b)
}
func (m *Persisted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persisted.Marshal(b, m, deterministic)
}
func (dst *Persisted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persisted.Merge(dst, src)
}
func (m *Persisted) XXX_Size() int {
	return xxx_messageInfo_Persisted.Size(m)
}
func (m *Persisted) XXX_DiscardUnknown() {
	xxx_messageInfo_Persisted.DiscardUnknown(m)
}

var xxx_messageInfo_Persisted proto.InternalMessageInfo

func (m *Persisted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Persisted) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *Persisted) GetPodNamespace() string {
	if m != nil {
		return m.PodNamespace
	}
	return ""
}

func (m *Persisted) GetVeth1Name() string {
	if m != nil {
		return m.Veth1Name
	}
	return ""
}

func (m *Persisted) GetVeth2Name() string {
	if m != nil {
		return m.Veth2Name
	}
	return ""
}

func (m *Persisted) GetVppIfName() string {
	if m != nil {
		return m.VppIfName
	}
	return ""
}

func (m *Persisted) GetPodTapName() string {
	if m != nil {
		return m.PodTapName
	}
	return ""
}

func (m *Persisted) GetVppARPEntryInterface() string {
	if m != nil {
		return m.VppARPEntryInterface
	}
	return ""
}

func (m *Persisted) GetVppARPEntryIP() string {
	if m != nil {
		return m.VppARPEntryIP
	}
	return ""
}

func (m *Persisted) GetPodARPEntryInterface() string {
	if m != nil {
		return m.PodARPEntryInterface
	}
	return ""
}

func (m *Persisted) GetPodARPEntryIP() string {
	if m != nil {
		return m.PodARPEntryIP
	}
	return ""
}

func (m *Persisted) GetVppRouteVrf() uint32 {
	if m != nil {
		return m.VppRouteVrf
	}
	return 0
}

func (m *Persisted) GetVppRouteDest() string {
	if m != nil {
		return m.VppRouteDest
	}
	return ""
}

func (m *Persisted) GetVppRouteNextHop() string {
	if m != nil {
		return m.VppRouteNextHop
	}
	return ""
}

func (m *Persisted) GetPodLinkRouteDest() string {
	if m != nil {
		return m.PodLinkRouteDest
	}
	return ""
}

func (m *Persisted) GetPodLinkRouteInterface() string {
	if m != nil {
		return m.PodLinkRouteInterface
	}
	return ""
}

func (m *Persisted) GetPodDefaultRouteInterface() string {
	if m != nil {
		return m.PodDefaultRouteInterface
	}
	return ""
}

func init() {
	proto.RegisterType((*Persisted)(nil), "container.Persisted")
}

func init() { proto.RegisterFile("container.proto", fileDescriptor_container_0c4ce2710ed9398e) }

var fileDescriptor_container_0c4ce2710ed9398e = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x69, 0xdf, 0xb7, 0x2d, 0x99, 0xfe, 0x75, 0xac, 0xb0, 0x07, 0x91, 0x52, 0x3c, 0x14,
	0x0f, 0x82, 0xd5, 0x93, 0x37, 0x21, 0x82, 0x01, 0x29, 0x4b, 0x90, 0xdc, 0x63, 0x77, 0x83, 0x45,
	0xcd, 0x2e, 0x9b, 0x2d, 0xe8, 0x07, 0xf1, 0xfb, 0x4a, 0x26, 0x4d, 0xb3, 0x69, 0xe3, 0x2d, 0xf3,
	0xfb, 0x3d, 0xf3, 0x90, 0x0c, 0x81, 0xf1, 0x5a, 0xa5, 0x36, 0xde, 0xa4, 0xd2, 0x5c, 0x6b, 0xa3,
	0xac, 0x42, 0x6f, 0x0f, 0xe6, 0x3f, 0x1d, 0xf0, 0xb8, 0x34, 0xd9, 0x26, 0xb3, 0x52, 0xe0, 0x08,
	0xda, 0x81, 0xcf, 0x5a, 0xb3, 0xd6, 0xc2, 0x0b, 0xdb, 0x81, 0x8f, 0x0c, 0x7a, 0x5a, 0x89, 0x55,
	0xfc, 0x29, 0x59, 0x9b, 0x60, 0x39, 0xe2, 0x1c, 0x06, 0xbb, 0xc7, 0x4c, 0xc7, 0x6b, 0xc9, 0xfe,
	0x91, 0xae, 0x31, 0x3c, 0x07, 0x2f, 0x92, 0xf6, 0xed, 0x86, 0xf6, 0xff, 0x53, 0xa0, 0x02, 0xa5,
	0x5d, 0x92, 0xed, 0x54, 0x76, 0xb9, 0xb7, 0x5a, 0x07, 0x09, 0xd9, 0xee, 0xce, 0x96, 0x00, 0x2f,
	0x00, 0xb8, 0x12, 0x2f, 0xb1, 0x26, 0xdd, 0x23, 0xed, 0x10, 0x5c, 0xc2, 0x34, 0xd2, 0xfa, 0x21,
	0xe4, 0x8f, 0xa9, 0x35, 0xdf, 0x41, 0x6a, 0xa5, 0x49, 0xf2, 0xb7, 0xec, 0x53, 0xb2, 0xd1, 0xe1,
	0x25, 0x0c, 0x5d, 0xce, 0xd9, 0x80, 0xc2, 0x75, 0x98, 0x37, 0x73, 0x25, 0x8e, 0x9b, 0x87, 0x45,
	0x73, 0x93, 0xcb, 0x9b, 0x5d, 0xce, 0xd9, 0xa8, 0x68, 0xae, 0x41, 0x9c, 0x41, 0x3f, 0xd2, 0x3a,
	0x54, 0x5b, 0x2b, 0x23, 0x93, 0xb0, 0xf1, 0xac, 0xb5, 0x18, 0x86, 0x2e, 0xca, 0x6f, 0x5e, 0x8e,
	0xbe, 0xcc, 0x2c, 0x9b, 0x14, 0x37, 0x77, 0x19, 0x2e, 0x60, 0x5c, 0xce, 0x2b, 0xf9, 0x65, 0x9f,
	0x94, 0x66, 0x27, 0x14, 0x3b, 0xc4, 0x78, 0x05, 0x13, 0xae, 0xc4, 0xf3, 0x26, 0x7d, 0xaf, 0x1a,
	0x91, 0xa2, 0x47, 0x1c, 0xef, 0xe0, 0xcc, 0x65, 0xd5, 0x67, 0x9f, 0xd2, 0x42, 0xb3, 0xc4, 0x7b,
	0x60, 0x5c, 0x09, 0x5f, 0x26, 0xf1, 0xf6, 0xc3, 0x1e, 0x2c, 0x4e, 0x69, 0xf1, 0x4f, 0xff, 0xda,
	0xa5, 0x3f, 0xf5, 0xf6, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xde, 0x94, 0x1f, 0xbc, 0x02, 0x00,
	0x00,
}
