// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivtelemetryv1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivtelemetry/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeContivTelemetryReports implements ContivTelemetryReportInterface
type FakeContivTelemetryReports struct {
	Fake *FakeContivtelemetryV1
	ns   string
}

var contivtelemetryreportsResource = schema.GroupVersionResource{Group: "contivtelemetry.vpp", Version: "v1", Resource: "contivtelemetryreports"}

var contivtelemetryreportsKind = schema.GroupVersionKind{Group: "contivtelemetry.vpp", Version: "v1", Kind: "ContivTelemetryReport"}

// Get takes name of the contivTelemetryReport, and returns the corresponding contivTelemetryReport object, and an error if there is any.
func (c *FakeContivTelemetryReports) Get(name string, options v1.GetOptions) (result *contivtelemetryv1.ContivTelemetryReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(contivtelemetryreportsResource, c.ns, name), &contivtelemetryv1.ContivTelemetryReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivtelemetryv1.ContivTelemetryReport), err
}

// List takes label and field selectors, and returns the list of ContivTelemetryReports that match those selectors.
func (c *FakeContivTelemetryReports) List(opts v1.ListOptions) (result *contivtelemetryv1.ContivTelemetryReportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(contivtelemetryreportsResource, contivtelemetryreportsKind, c.ns, opts), &contivtelemetryv1.ContivTelemetryReportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivtelemetryv1.ContivTelemetryReportList{ListMeta: obj.(*contivtelemetryv1.ContivTelemetryReportList).ListMeta}
	for _, item := range obj.(*contivtelemetryv1.ContivTelemetryReportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested contivTelemetryReports.
func (c *FakeContivTelemetryReports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(contivtelemetryreportsResource, c.ns, opts))

}

// Create takes the representation of a contivTelemetryReport and creates it.  Returns the server's representation of the contivTelemetryReport, and an error, if there is any.
func (c *FakeContivTelemetryReports) Create(contivTelemetryReport *contivtelemetryv1.ContivTelemetryReport) (result *contivtelemetryv1.ContivTelemetryReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(contivtelemetryreportsResource, c.ns, contivTelemetryReport), &contivtelemetryv1.ContivTelemetryReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivtelemetryv1.ContivTelemetryReport), err
}

// Update takes the representation of a contivTelemetryReport and updates it. Returns the server's representation of the contivTelemetryReport, and an error, if there is any.
func (c *FakeContivTelemetryReports) Update(contivTelemetryReport *contivtelemetryv1.ContivTelemetryReport) (result *contivtelemetryv1.ContivTelemetryReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(contivtelemetryreportsResource, c.ns, contivTelemetryReport), &contivtelemetryv1.ContivTelemetryReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivtelemetryv1.ContivTelemetryReport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeContivTelemetryReports) UpdateStatus(contivTelemetryReport *contivtelemetryv1.ContivTelemetryReport) (*contivtelemetryv1.ContivTelemetryReport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(contivtelemetryreportsResource, "status", c.ns, contivTelemetryReport), &contivtelemetryv1.ContivTelemetryReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivtelemetryv1.ContivTelemetryReport), err
}

// Delete takes name of the contivTelemetryReport and deletes it. Returns an error if one occurs.
func (c *FakeContivTelemetryReports) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(contivtelemetryreportsResource, c.ns, name), &contivtelemetryv1.ContivTelemetryReport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeContivTelemetryReports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(contivtelemetryreportsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivtelemetryv1.ContivTelemetryReportList{})
	return err
}

// Patch applies the patch and returns the patched contivTelemetryReport.
func (c *FakeContivTelemetryReports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivtelemetryv1.ContivTelemetryReport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(contivtelemetryreportsResource, c.ns, name, data, subresources...), &contivtelemetryv1.ContivTelemetryReport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivtelemetryv1.ContivTelemetryReport), err
}
