---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: linux-chain3
spec:
  chain:
    - name: CNF 9
      type: Pod
      podSelector:
        cnf: linux-cnf9
      outputInterface: tap1

    - name: CNF 10
      type: Pod
      podSelector:
        cnf: linux-cnf10
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 11
      type: Pod
      podSelector:
        cnf: linux-cnf11
      inputInterface: tap1
      outputInterface: tap2


    - name: CNF 12
      type: Pod
      podSelector:
        cnf: linux-cnf12
      inputInterface: tap1
