---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: linux-chain2
spec:
  chain:
    - name: CNF 7
      type: Pod
      podSelector:
        cnf: linux-cnf7
      outputInterface: tap1

    - name: CNF 8
      type: Pod
      podSelector:
        cnf: linux-cnf8
      inputInterface: tap1
