---
apiVersion: contivpp.io/v1
kind: ServiceFunctionChain
metadata:
  name: linux-chain
spec:
  chain:
    - name: CNF 1
      type: Pod
      podSelector:
        cnf: linux-cnf1
      outputInterface: tap1

    - name: CNF 2
      type: Pod
      podSelector:
        cnf: linux-cnf2
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 3
      type: Pod
      podSelector:
        cnf: linux-cnf3
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 4
      type: Pod
      podSelector:
        cnf: linux-cnf4
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 5
      type: Pod
      podSelector:
        cnf: linux-cnf5
      inputInterface: tap1
      outputInterface: tap2

    - name: CNF 6
      type: Pod
      podSelector:
        cnf: linux-cnf6
      inputInterface: tap1
