#!/bin/bash

set -euo pipefail
. ./defaults

VBoxManage dhcpserver remove --netname vpp || :
echo "Creating VirtualBox DHCP server..."
VBoxManage dhcpserver add --netname vpp --ip 192.168.16.1 --netmask 255.255.255.0 --lowerip 192.168.16.2 --upperip 192.168.16.254 --enable

vagrant up
