#!/bin/bash

set -euo pipefail

if [ -f ./config/init ] ; then
    rm ./config/init
fi
touch ./config/init

if [ -f ./config/cert ] ; then
    rm ./config/cert
fi
touch ./config/cert

if [ -f ../k8s/contiv-vpp/manifest.yaml ] ; then
    rm ../k8s/contiv-vpp/manifest.yaml
fi

if [ -f ./config/*.tar ] ; then
    rm ./config/*.tar
fi

vagrant destroy -f
vagrant destroy -f

rm -rf ./.vagrant

if [ -f .vagrant-state ] ; then
    rm .vagrant-state
fi
