#!/bin/bash

set -euo pipefail

export K8S_NODE_OS=${K8S_NODE_OS:-ubuntu}
export K8S_NODES=${K8S_NODES:-1}

while true
do
read -r -p "Please provide the number of workers for the Kubernetes cluster (0-50) or enter [Q/q] to exit: " input

if [ $input -eq $input 2>/dev/null ]
then
  if (( $input >= 0 && $input <= 50))
  then
    export K8S_NODES=$input
    break
  else
    echo "Input out of range, please try again..."
  fi
elif [ $input == "q" ] || [ $input == "Q" ]
then
 echo "Exiting..."
 exit 0
else
 echo "$input is not a valid input"
fi
done
echo
echo 'Please choose vagrant provider: '
PS3='--> '
options=("VirtualBox" "VMWare_Fusion" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "VirtualBox")
            echo "You chose VirtualBox"
            export VAGRANT_DEFAULT_PROVIDER="virtualbox"
            break
            ;;
        "VMWare_Fusion")
            echo "You chose VMWare_Fusion"
            export VAGRANT_DEFAULT_PROVIDER="vmware_fusion"
            break
            ;;
        "Quit")
            echo "Exiting..."
            exit 0
            ;;
        *) echo invalid option;;
    esac
done
echo

echo 'Please choose Kubernetes environment: '
PS3='--> '
options=("Production" "Development" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Production")
            echo "You chose Production environment"
            export K8S_DEPLOYMENT_ENV="prod"
            break
            ;;
        "Development")
            echo "You chose Development environment"
            export K8S_DEPLOYMENT_ENV="dev"
            break
            ;;
        "Quit")
            echo "Exiting..."
            exit 0
            ;;
        *) echo invalid option;;
    esac
done
echo

echo 'Please choose deployment scenario: '
PS3='--> '
options=("Without StealFirstNIC" "With StealFirstNIC" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Without StealFirstNIC")
            echo "You chose deployment without StealFirstNIC"
            export K8S_DEPLOYMENT_SCENARIO="nostn"
            break
            ;;
        "With StealFirstNIC")
            echo "You chose deployment with StealFirstNIC"
            export K8S_DEPLOYMENT_SCENARIO="stn"
            break
            ;;
        "Quit")
            echo "Exiting..."
            exit 0
            ;;
        *) echo invalid option;;
    esac
done

if [ "$K8S_DEPLOYMENT_ENV" == "prod" ]; then 
    DEP_ENV="production"
else 
    DEP_ENV="development"
fi

if [ "$K8S_DEPLOYMENT_SCENARIO" == "nostn" ]; then
    DEP_SCEN="without STN"
else 
    DEP_SCEN="with STN"
fi
echo
echo "Creating a $VAGRANT_DEFAULT_PROVIDER $DEP_ENV environment, $DEP_SCEN and $K8S_NODES worker node(s)"
echo 
vagrant up
