// Code generated by 'create-test-data.sh' on Thu Oct  4 15:14:26 PDT 2018. DO NOT EDIT.
//
// Image versions:
// - k8s-worker1:	v1.4-alpha-185-g547ddf9
// - k8s-master:	v1.4-alpha-185-g547ddf9
// - k8s-worker2:	v1.4-alpha-185-g547ddf9

package testdata

type rawNodeTestData map[string]map[string]string

func getRawNodeTestData() rawNodeTestData {
	return rawNodeTestData{
		"k8s-worker1": {
			"nodeinfo": `{
				"id": 2,
				"ip_address": "192.168.16.2/24",
				"management_ip_address": "10.20.0.10",
				"name": "k8s-worker1"
			}`,
			"liveness": `{
				"build_date": "2018-10-04T04:15+00:00",
				"build_version": "v1.4-alpha-185-g547ddf9",
				"commit_hash": "v1.4-alpha-185-g547ddf9",
				"last_change": 1538635481,
				"last_update": 1538691261,
				"plugins": [
					{
						"name": "govpp",
						"state": 1
					},
					{
						"name": "vpp",
						"state": 1
					}
				],
				"start_time": 1538635480,
				"state": 1
			}`,
			"ipam": `{
				"config": {
					"nodeInterconnectCIDR": "192.168.16.0/24",
					"nodeInterconnectDHCP": false,
					"podIfIPCIDR": "10.2.1.0/24",
					"podNetworkPrefixLen": 24,
					"podSubnetCIDR": "10.1.0.0/16",
					"serviceCIDR": "10.96.0.0/12",
					"vppHostNetworkPrefixLen": 24,
					"vppHostSubnetCIDR": "172.30.0.0/16",
					"vxlanCIDR": "192.168.30.0/24"
				},
				"nodeIP": "192.168.16.2",
				"nodeId": 2,
				"nodeName": "k8s-worker1",
				"podNetwork": "10.1.2.0/24",
				"vppHostNetwork": "172.30.2.0/24"
			}`,
			"interfaces": `{
				"0": {
					"interface": {
						"name": "local0"
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "local0",
						"sw_if_index": 0,
						"tag": "local0"
					}
				},
				"1": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"192.168.16.2/24"
						],
						"mtu": 9202,
						"name": "GigabitEthernet0/8/0",
						"phys_address": "08:00:27:94:67:a2",
						"type": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "GigabitEthernet0/8/0",
						"sw_if_index": 1,
						"tag": "GigabitEthernet0/8/0"
					}
				},
				"2": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"172.30.2.1/24"
						],
						"mtu": 1450,
						"name": "tap-vpp2",
						"phys_address": "01:23:45:67:89:42",
						"tap": {
							"version": 2
						},
						"type": 3
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "tap0",
						"sw_if_index": 2,
						"tag": "tap-vpp2"
					}
				},
				"3": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"192.168.30.2/24"
						],
						"name": "vxlanBVI",
						"phys_address": "1a:2b:3c:4d:5e:02",
						"vrf": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "loop0",
						"sw_if_index": 3,
						"tag": "vxlanBVI"
					}
				},
				"4": {
					"interface": {
						"enabled": true,
						"name": "vxlan1",
						"type": 5,
						"vxlan": {
							"dst_address": "192.168.16.1",
							"multicast": "local0",
							"src_address": "192.168.16.2",
							"vni": 10
						}
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "vxlan_tunnel0",
						"sw_if_index": 4,
						"tag": "vxlan1"
					}
				},
				"5": {
					"interface": {
						"enabled": true,
						"name": "vxlan3",
						"type": 5,
						"vxlan": {
							"dst_address": "192.168.16.3",
							"multicast": "local0",
							"src_address": "192.168.16.2",
							"vni": 10
						}
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "vxlan_tunnel1",
						"sw_if_index": 5,
						"tag": "vxlan3"
					}
				},
				"6": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"10.2.1.2/32"
						],
						"mtu": 1450,
						"name": "tap49cf4eba7d53559",
						"phys_address": "02:fe:fc:07:21:82",
						"tap": {
							"version": 2
						},
						"type": 3,
						"vrf": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "tap1",
						"sw_if_index": 6,
						"tag": "tap49cf4eba7d53559"
					}
				}
			}`,
			"bridgedomains": `{
				"1": {
					"bridge_domain": {
						"forward": true,
						"interfaces": [
							{
								"bridged_virtual_interface": true,
								"name": "vxlanBVI",
								"split_horizon_group": 1
							},
							{
								"name": "vxlan1",
								"split_horizon_group": 1
							},
							{
								"name": "vxlan3",
								"split_horizon_group": 1
							}
						],
						"name": "vxlanBD"
					},
					"bridge_domain_meta": {
						"bridge_domain_id": 1,
						"bridge_domain_id_to_name": {
							"3": "vxlanBVI",
							"4": "vxlan1",
							"5": "vxlan3"
						}
					}
				}
			}`,
			"l2fib": `{
				"1a:2b:3c:4d:5e:01": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"outgoing_interface": "vxlan1",
						"phys_address": "1a:2b:3c:4d:5e:01",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 4
					}
				},
				"1a:2b:3c:4d:5e:02": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"bridged_virtual_interface": true,
						"outgoing_interface": "vxlanBVI",
						"phys_address": "1a:2b:3c:4d:5e:02",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 3
					}
				},
				"1a:2b:3c:4d:5e:03": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"outgoing_interface": "vxlan3",
						"phys_address": "1a:2b:3c:4d:5e:03",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 5
					}
				}
			}`,
			"arps": `[
				{
					"Arp": {
						"interface": "vxlanBVI",
						"ip_address": "192.168.30.1",
						"phys_address": "1a:2b:3c:4d:5e:01",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 3
					}
				},
				{
					"Arp": {
						"interface": "vxlanBVI",
						"ip_address": "192.168.30.3",
						"phys_address": "1a:2b:3c:4d:5e:03",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 3
					}
				},
				{
					"Arp": {
						"interface": "tap-vpp2",
						"ip_address": "172.30.2.2",
						"phys_address": "86:24:d1:82:88:89"
					},
					"Meta": {
						"SwIfIndex": 2
					}
				},
				{
					"Arp": {
						"interface": "tap49cf4eba7d53559",
						"ip_address": "10.1.2.2",
						"phys_address": "00:00:00:00:00:02",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 6
					}
				}
]`,
			"routes": `[
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/0",
						"next_hop_addr": "192.168.16.100",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/0",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.0.2.15/32",
						"next_hop_addr": "172.30.2.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.1.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.1.0/24",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 6,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.2.2/32",
						"next_hop_addr": "10.1.2.2",
						"outgoing_interface": "tap49cf4eba7d53559",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.3.0/24",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 6,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.2.1.2/32",
						"next_hop_addr": "10.2.1.2",
						"outgoing_interface": "tap49cf4eba7d53559",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.2/32",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.2/32",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.10/32",
						"next_hop_addr": "172.30.2.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.11/32",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.11/32",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.0/24",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.0/24",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.1/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.1/32",
						"next_hop_addr": "172.30.2.1",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.2/32",
						"next_hop_addr": "172.30.2.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.0/24",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.1/32",
						"next_hop_addr": "192.168.16.1",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.2/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.2/32",
						"next_hop_addr": "192.168.16.2",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 6,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.2/32",
						"next_hop_addr": "192.168.16.2",
						"outgoing_interface": "tap49cf4eba7d53559",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.3/32",
						"next_hop_addr": "192.168.16.3",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.2/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.2/32",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "224.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "224.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "240.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "240.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "255.255.255.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "255.255.255.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 2,
						"IsDvr": false,
						"IsIPv6": true,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv6-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "::/0",
						"next_hop_addr": "::",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 2,
						"IsDvr": false,
						"IsIPv6": true,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv6-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "fe80::/10",
						"next_hop_addr": "::",
						"weight": 1
					}
				}
]`,
		},
		"k8s-master": {
			"nodeinfo": `{
				"id": 1,
				"ip_address": "192.168.16.1/24",
				"management_ip_address": "10.20.0.2",
				"name": "k8s-master"
			}`,
			"liveness": `{
				"build_date": "2018-10-04T04:15+00:00",
				"build_version": "v1.4-alpha-185-g547ddf9",
				"commit_hash": "v1.4-alpha-185-g547ddf9",
				"last_change": 1538635194,
				"last_update": 1538691259,
				"plugins": [
					{
						"name": "govpp",
						"state": 1
					},
					{
						"name": "vpp",
						"state": 1
					}
				],
				"start_time": 1538635193,
				"state": 1
			}`,
			"ipam": `{
				"config": {
					"nodeInterconnectCIDR": "192.168.16.0/24",
					"nodeInterconnectDHCP": false,
					"podIfIPCIDR": "10.2.1.0/24",
					"podNetworkPrefixLen": 24,
					"podSubnetCIDR": "10.1.0.0/16",
					"serviceCIDR": "10.96.0.0/12",
					"vppHostNetworkPrefixLen": 24,
					"vppHostSubnetCIDR": "172.30.0.0/16",
					"vxlanCIDR": "192.168.30.0/24"
				},
				"nodeIP": "192.168.16.1",
				"nodeId": 1,
				"nodeName": "k8s-master",
				"podNetwork": "10.1.1.0/24",
				"vppHostNetwork": "172.30.1.0/24"
			}`,
			"interfaces": `{
				"0": {
					"interface": {
						"name": "local0"
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "local0",
						"sw_if_index": 0,
						"tag": "local0"
					}
				},
				"1": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"192.168.16.1/24"
						],
						"mtu": 9202,
						"name": "GigabitEthernet0/8/0",
						"phys_address": "08:00:27:0c:6c:dd",
						"type": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "GigabitEthernet0/8/0",
						"sw_if_index": 1,
						"tag": "GigabitEthernet0/8/0"
					}
				},
				"2": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"172.30.1.1/24"
						],
						"mtu": 1450,
						"name": "tap-vpp2",
						"phys_address": "01:23:45:67:89:42",
						"tap": {
							"version": 2
						},
						"type": 3
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "tap0",
						"sw_if_index": 2,
						"tag": "tap-vpp2"
					}
				},
				"3": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"192.168.30.1/24"
						],
						"name": "vxlanBVI",
						"phys_address": "1a:2b:3c:4d:5e:01",
						"vrf": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "loop0",
						"sw_if_index": 3,
						"tag": "vxlanBVI"
					}
				},
				"4": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"10.2.1.2/32"
						],
						"mtu": 1450,
						"name": "tapb8c32b6e28252ba",
						"phys_address": "02:fe:fc:07:21:82",
						"tap": {
							"version": 2
						},
						"type": 3,
						"vrf": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "tap1",
						"sw_if_index": 4,
						"tag": "tapb8c32b6e28252ba"
					}
				},
				"5": {
					"interface": {
						"enabled": true,
						"name": "vxlan2",
						"type": 5,
						"vxlan": {
							"dst_address": "192.168.16.2",
							"multicast": "local0",
							"src_address": "192.168.16.1",
							"vni": 10
						}
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "vxlan_tunnel0",
						"sw_if_index": 5,
						"tag": "vxlan2"
					}
				},
				"6": {
					"interface": {
						"enabled": true,
						"name": "vxlan3",
						"type": 5,
						"vxlan": {
							"dst_address": "192.168.16.3",
							"multicast": "local0",
							"src_address": "192.168.16.1",
							"vni": 10
						}
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "vxlan_tunnel1",
						"sw_if_index": 6,
						"tag": "vxlan3"
					}
				}
			}`,
			"bridgedomains": `{
				"1": {
					"bridge_domain": {
						"forward": true,
						"interfaces": [
							{
								"bridged_virtual_interface": true,
								"name": "vxlanBVI",
								"split_horizon_group": 1
							},
							{
								"name": "vxlan2",
								"split_horizon_group": 1
							},
							{
								"name": "vxlan3",
								"split_horizon_group": 1
							}
						],
						"name": "vxlanBD"
					},
					"bridge_domain_meta": {
						"bridge_domain_id": 1,
						"bridge_domain_id_to_name": {
							"3": "vxlanBVI",
							"5": "vxlan2",
							"6": "vxlan3"
						}
					}
				}
			}`,
			"l2fib": `{
				"1a:2b:3c:4d:5e:01": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"bridged_virtual_interface": true,
						"outgoing_interface": "vxlanBVI",
						"phys_address": "1a:2b:3c:4d:5e:01",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 3
					}
				},
				"1a:2b:3c:4d:5e:02": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"outgoing_interface": "vxlan2",
						"phys_address": "1a:2b:3c:4d:5e:02",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 5
					}
				},
				"1a:2b:3c:4d:5e:03": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"outgoing_interface": "vxlan3",
						"phys_address": "1a:2b:3c:4d:5e:03",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 6
					}
				}
			}`,
			"arps": `[
				{
					"Arp": {
						"interface": "vxlanBVI",
						"ip_address": "192.168.30.2",
						"phys_address": "1a:2b:3c:4d:5e:02",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 3
					}
				},
				{
					"Arp": {
						"interface": "vxlanBVI",
						"ip_address": "192.168.30.3",
						"phys_address": "1a:2b:3c:4d:5e:03",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 3
					}
				},
				{
					"Arp": {
						"interface": "tap-vpp2",
						"ip_address": "172.30.1.2",
						"phys_address": "ee:33:fd:c4:63:6e"
					},
					"Meta": {
						"SwIfIndex": 2
					}
				},
				{
					"Arp": {
						"interface": "tapb8c32b6e28252ba",
						"ip_address": "10.1.1.2",
						"phys_address": "00:00:00:00:00:02",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 4
					}
				}
]`,
			"routes": `[
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/0",
						"next_hop_addr": "192.168.16.100",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/0",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.0.2.15/32",
						"next_hop_addr": "172.30.1.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.1.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.1.2/32",
						"next_hop_addr": "10.1.1.2",
						"outgoing_interface": "tapb8c32b6e28252ba",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.2.0/24",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.3.0/24",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.2.1.2/32",
						"next_hop_addr": "10.2.1.2",
						"outgoing_interface": "tapb8c32b6e28252ba",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.2/32",
						"next_hop_addr": "172.30.1.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.10/32",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.10/32",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.11/32",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.11/32",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.0/24",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.1/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.1/32",
						"next_hop_addr": "172.30.1.1",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.2/32",
						"next_hop_addr": "172.30.1.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.0/24",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.0/24",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.1/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.1/32",
						"next_hop_addr": "192.168.16.1",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.1/32",
						"next_hop_addr": "192.168.16.1",
						"outgoing_interface": "tapb8c32b6e28252ba",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.2/32",
						"next_hop_addr": "192.168.16.2",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.3/32",
						"next_hop_addr": "192.168.16.3",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.1/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.1/32",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "224.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "224.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "240.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "240.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "255.255.255.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "255.255.255.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 2,
						"IsDvr": false,
						"IsIPv6": true,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv6-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "::/0",
						"next_hop_addr": "::",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 2,
						"IsDvr": false,
						"IsIPv6": true,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv6-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "fe80::/10",
						"next_hop_addr": "::",
						"weight": 1
					}
				}
]`,
		},
		"k8s-worker2": {
			"nodeinfo": `{
				"id": 3,
				"ip_address": "192.168.16.3/24",
				"management_ip_address": "10.20.0.11",
				"name": "k8s-worker2"
			}`,
			"liveness": `{
				"build_date": "2018-10-04T04:15+00:00",
				"build_version": "v1.4-alpha-185-g547ddf9",
				"commit_hash": "v1.4-alpha-185-g547ddf9",
				"last_change": 1538635484,
				"last_update": 1538691261,
				"plugins": [
					{
						"name": "govpp",
						"state": 1
					},
					{
						"name": "vpp",
						"state": 1
					}
				],
				"start_time": 1538635483,
				"state": 1
			}`,
			"ipam": `{
				"config": {
					"nodeInterconnectCIDR": "192.168.16.0/24",
					"nodeInterconnectDHCP": false,
					"podIfIPCIDR": "10.2.1.0/24",
					"podNetworkPrefixLen": 24,
					"podSubnetCIDR": "10.1.0.0/16",
					"serviceCIDR": "10.96.0.0/12",
					"vppHostNetworkPrefixLen": 24,
					"vppHostSubnetCIDR": "172.30.0.0/16",
					"vxlanCIDR": "192.168.30.0/24"
				},
				"nodeIP": "192.168.16.3",
				"nodeId": 3,
				"nodeName": "k8s-worker2",
				"podNetwork": "10.1.3.0/24",
				"vppHostNetwork": "172.30.3.0/24"
			}`,
			"interfaces": `{
				"0": {
					"interface": {
						"name": "local0"
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "local0",
						"sw_if_index": 0,
						"tag": "local0"
					}
				},
				"1": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"192.168.16.3/24"
						],
						"mtu": 9202,
						"name": "GigabitEthernet0/8/0",
						"phys_address": "08:00:27:2c:20:16",
						"type": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "GigabitEthernet0/8/0",
						"sw_if_index": 1,
						"tag": "GigabitEthernet0/8/0"
					}
				},
				"2": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"172.30.3.1/24"
						],
						"mtu": 1450,
						"name": "tap-vpp2",
						"phys_address": "01:23:45:67:89:42",
						"tap": {
							"version": 2
						},
						"type": 3
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "tap0",
						"sw_if_index": 2,
						"tag": "tap-vpp2"
					}
				},
				"3": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"192.168.30.3/24"
						],
						"name": "vxlanBVI",
						"phys_address": "1a:2b:3c:4d:5e:03",
						"vrf": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "loop0",
						"sw_if_index": 3,
						"tag": "vxlanBVI"
					}
				},
				"4": {
					"interface": {
						"enabled": true,
						"name": "vxlan1",
						"type": 5,
						"vxlan": {
							"dst_address": "192.168.16.1",
							"multicast": "local0",
							"src_address": "192.168.16.3",
							"vni": 10
						}
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "vxlan_tunnel0",
						"sw_if_index": 4,
						"tag": "vxlan1"
					}
				},
				"5": {
					"interface": {
						"enabled": true,
						"name": "vxlan2",
						"type": 5,
						"vxlan": {
							"dst_address": "192.168.16.2",
							"multicast": "local0",
							"src_address": "192.168.16.3",
							"vni": 10
						}
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "vxlan_tunnel1",
						"sw_if_index": 5,
						"tag": "vxlan2"
					}
				},
				"6": {
					"interface": {
						"enabled": true,
						"ip_addresses": [
							"10.2.1.2/32"
						],
						"mtu": 1450,
						"name": "tap1eb93d047981f1b",
						"phys_address": "02:fe:fc:07:21:82",
						"tap": {
							"version": 2
						},
						"type": 3,
						"vrf": 1
					},
					"interface_meta": {
						"dhcp": null,
						"internal_name": "tap1",
						"sw_if_index": 6,
						"tag": "tap1eb93d047981f1b"
					}
				}
			}`,
			"bridgedomains": `{
				"1": {
					"bridge_domain": {
						"forward": true,
						"interfaces": [
							{
								"bridged_virtual_interface": true,
								"name": "vxlanBVI",
								"split_horizon_group": 1
							},
							{
								"name": "vxlan1",
								"split_horizon_group": 1
							},
							{
								"name": "vxlan2",
								"split_horizon_group": 1
							}
						],
						"name": "vxlanBD"
					},
					"bridge_domain_meta": {
						"bridge_domain_id": 1,
						"bridge_domain_id_to_name": {
							"3": "vxlanBVI",
							"4": "vxlan1",
							"5": "vxlan2"
						}
					}
				}
			}`,
			"l2fib": `{
				"1a:2b:3c:4d:5e:01": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"outgoing_interface": "vxlan1",
						"phys_address": "1a:2b:3c:4d:5e:01",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 4
					}
				},
				"1a:2b:3c:4d:5e:02": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"outgoing_interface": "vxlan2",
						"phys_address": "1a:2b:3c:4d:5e:02",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 5
					}
				},
				"1a:2b:3c:4d:5e:03": {
					"fib": {
						"bridge_domain": "vxlanBD",
						"bridged_virtual_interface": true,
						"outgoing_interface": "vxlanBVI",
						"phys_address": "1a:2b:3c:4d:5e:03",
						"static_config": true
					},
					"fib_meta": {
						"bridge_domain_id": 1,
						"outgoing_interface_sw_if_idx": 3
					}
				}
			}`,
			"arps": `[
				{
					"Arp": {
						"interface": "vxlanBVI",
						"ip_address": "192.168.30.1",
						"phys_address": "1a:2b:3c:4d:5e:01",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 3
					}
				},
				{
					"Arp": {
						"interface": "vxlanBVI",
						"ip_address": "192.168.30.2",
						"phys_address": "1a:2b:3c:4d:5e:02",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 3
					}
				},
				{
					"Arp": {
						"interface": "tap-vpp2",
						"ip_address": "172.30.3.2",
						"phys_address": "5a:81:39:5d:21:eb"
					},
					"Meta": {
						"SwIfIndex": 2
					}
				},
				{
					"Arp": {
						"interface": "tap1eb93d047981f1b",
						"ip_address": "10.1.3.2",
						"phys_address": "00:00:00:00:00:02",
						"static": true
					},
					"Meta": {
						"SwIfIndex": 6
					}
				}
]`,
			"routes": `[
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/0",
						"next_hop_addr": "192.168.16.100",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/0",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "0.0.0.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.0.2.15/32",
						"next_hop_addr": "172.30.3.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.1.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.1.0/24",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.2.0/24",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 6,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.1.3.2/32",
						"next_hop_addr": "10.1.3.2",
						"outgoing_interface": "tap1eb93d047981f1b",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 6,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.2.1.2/32",
						"next_hop_addr": "10.2.1.2",
						"outgoing_interface": "tap1eb93d047981f1b",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.2/32",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.2/32",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.10/32",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.10/32",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "10.20.0.11/32",
						"next_hop_addr": "172.30.3.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"via_vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.0.0/16",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.1.0/24",
						"next_hop_addr": "192.168.30.1",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.2.0/24",
						"next_hop_addr": "192.168.30.2",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.0/24",
						"next_hop_addr": "0.0.0.0",
						"type": 1,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.1/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.1/32",
						"next_hop_addr": "172.30.3.1",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 2,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.2/32",
						"next_hop_addr": "172.30.3.2",
						"outgoing_interface": "tap-vpp2",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "172.30.3.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.1/32",
						"next_hop_addr": "192.168.16.1",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.2/32",
						"next_hop_addr": "192.168.16.2",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.3/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 1,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.3/32",
						"next_hop_addr": "192.168.16.3",
						"outgoing_interface": "GigabitEthernet0/8/0",
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 6,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.3/32",
						"next_hop_addr": "192.168.16.3",
						"outgoing_interface": "tap1eb93d047981f1b",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "192.168.16.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.0/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.3/24",
						"next_hop_addr": "0.0.0.0",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": true,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 3,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.3/32",
						"next_hop_addr": "192.168.30.3",
						"outgoing_interface": "vxlanBVI",
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "192.168.30.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "224.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "224.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "240.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "240.0.0.0/4",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "255.255.255.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 1,
						"IsDvr": false,
						"IsIPv6": false,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv4-VRF:1"
					},
					"Route": {
						"dst_ip_addr": "255.255.255.255/32",
						"next_hop_addr": "0.0.0.0",
						"type": 2,
						"vrf_id": 1,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 2,
						"IsDvr": false,
						"IsIPv6": true,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv6-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "::/0",
						"next_hop_addr": "::",
						"type": 2,
						"weight": 1
					}
				},
				{
					"Meta": {
						"Afi": 2,
						"IsDvr": false,
						"IsIPv6": true,
						"IsLocal": false,
						"IsProhibit": false,
						"IsResolveAttached": false,
						"IsResolveHost": false,
						"IsSourceLookup": false,
						"IsUDPEncap": false,
						"IsUnreach": false,
						"LabelStack": [],
						"NextHopID": 0,
						"OutgoingIfIdx": 4294967295,
						"RpfID": 0,
						"TableName": "ipv6-VRF:0"
					},
					"Route": {
						"dst_ip_addr": "fe80::/10",
						"next_hop_addr": "::",
						"weight": 1
					}
				}
]`,
		},
	}
}
