// Code generated by 'create-test-data.sh' on Fri Aug 31 22:42:46 PDT 2018. DO NOT EDIT.

package testdata

func getRawK8sNodeTestData() []string {
	return []string{

		`{
			"addresses": [
				{
					"address": "10.20.0.2",
					"type": 3
				},
				{
					"address": "k8s-master",
					"type": 1
				}
			],
			"name": "k8s-master",
			"node_info": {
				"Architecture": "amd64",
				"KubeProxyVersion": "v1.10.5",
				"OperatingSystem": "linux",
				"boot_ID": "cdf79648-0832-4fbb-bb06-cf1a8b39f5ca",
				"container_runtime_version": "docker://18.6.0",
				"kernel_version": "4.4.0-21-generic",
				"kubelet_version": "v1.10.5",
				"machine_ID": "91550c3d3d1bca06c11d4f64575584db",
				"os_image": "Ubuntu 16.04 LTS",
				"system_UUID": "9219F9BC-7C45-40EB-9EBD-0BB0C8B95DB3"
			},
			"pod_CIDR": "10.0.0.0/24"
		}`,
		`{
			"addresses": [
				{
					"address": "10.20.0.10",
					"type": 3
				},
				{
					"address": "k8s-worker1",
					"type": 1
				}
			],
			"name": "k8s-worker1",
			"node_info": {
				"Architecture": "amd64",
				"KubeProxyVersion": "v1.10.5",
				"OperatingSystem": "linux",
				"boot_ID": "c5bcb9db-4344-4c83-9252-c5003417002d",
				"container_runtime_version": "docker://18.6.0",
				"kernel_version": "4.4.0-21-generic",
				"kubelet_version": "v1.10.5",
				"machine_ID": "91550c3d3d1bca06c11d4f64575584db",
				"os_image": "Ubuntu 16.04 LTS",
				"system_UUID": "3AA22D0A-1CE6-4FB8-9255-A517DA89EF70"
			},
			"pod_CIDR": "10.0.1.0/24"
		}`,
		`{
			"addresses": [
				{
					"address": "10.20.0.11",
					"type": 3
				},
				{
					"address": "k8s-worker2",
					"type": 1
				}
			],
			"name": "k8s-worker2",
			"node_info": {
				"Architecture": "amd64",
				"KubeProxyVersion": "v1.10.5",
				"OperatingSystem": "linux",
				"boot_ID": "b355c388-bef8-4b7d-ba64-658f2d52367c",
				"container_runtime_version": "docker://18.6.0",
				"kernel_version": "4.4.0-21-generic",
				"kubelet_version": "v1.10.5",
				"machine_ID": "91550c3d3d1bca06c11d4f64575584db",
				"os_image": "Ubuntu 16.04 LTS",
				"system_UUID": "6A452CEA-8506-49A7-904B-083C8E7925B7"
			},
			"pod_CIDR": "10.0.2.0/24"
		}`,
	}
}
