// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ipalloc.proto

package ipalloc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CustomPodInterface represents pod IP allocation made for a custom pod interface.
type CustomPodInterface struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Network              string   `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	IpAddress            string   `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	ServiceEndpoint      bool     `protobuf:"varint,4,opt,name=service_endpoint,json=serviceEndpoint,proto3" json:"service_endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomPodInterface) Reset()         { *m = CustomPodInterface{} }
func (m *CustomPodInterface) String() string { return proto.CompactTextString(m) }
func (*CustomPodInterface) ProtoMessage()    {}
func (*CustomPodInterface) Descriptor() ([]byte, []int) {
	return fileDescriptor_20954971669de07a, []int{0}
}

func (m *CustomPodInterface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomPodInterface.Unmarshal(m, b)
}
func (m *CustomPodInterface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomPodInterface.Marshal(b, m, deterministic)
}
func (m *CustomPodInterface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomPodInterface.Merge(m, src)
}
func (m *CustomPodInterface) XXX_Size() int {
	return xxx_messageInfo_CustomPodInterface.Size(m)
}
func (m *CustomPodInterface) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomPodInterface.DiscardUnknown(m)
}

var xxx_messageInfo_CustomPodInterface proto.InternalMessageInfo

func (m *CustomPodInterface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustomPodInterface) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *CustomPodInterface) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *CustomPodInterface) GetServiceEndpoint() bool {
	if m != nil {
		return m.ServiceEndpoint
	}
	return false
}

// CustomIPAllocation represents pod IP allocation made for custom purposes (other than the main pod IP address).
// It is used for persisting IP allocation of pods with multiple interfaces and multiple IP addresses.
type CustomIPAllocation struct {
	PodName              string                `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace         string                `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	CustomInterfaces     []*CustomPodInterface `protobuf:"bytes,3,rep,name=custom_interfaces,json=customInterfaces,proto3" json:"custom_interfaces,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CustomIPAllocation) Reset()         { *m = CustomIPAllocation{} }
func (m *CustomIPAllocation) String() string { return proto.CompactTextString(m) }
func (*CustomIPAllocation) ProtoMessage()    {}
func (*CustomIPAllocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_20954971669de07a, []int{1}
}

func (m *CustomIPAllocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomIPAllocation.Unmarshal(m, b)
}
func (m *CustomIPAllocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomIPAllocation.Marshal(b, m, deterministic)
}
func (m *CustomIPAllocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomIPAllocation.Merge(m, src)
}
func (m *CustomIPAllocation) XXX_Size() int {
	return xxx_messageInfo_CustomIPAllocation.Size(m)
}
func (m *CustomIPAllocation) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomIPAllocation.DiscardUnknown(m)
}

var xxx_messageInfo_CustomIPAllocation proto.InternalMessageInfo

func (m *CustomIPAllocation) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *CustomIPAllocation) GetPodNamespace() string {
	if m != nil {
		return m.PodNamespace
	}
	return ""
}

func (m *CustomIPAllocation) GetCustomInterfaces() []*CustomPodInterface {
	if m != nil {
		return m.CustomInterfaces
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomPodInterface)(nil), "ipalloc.CustomPodInterface")
	proto.RegisterType((*CustomIPAllocation)(nil), "ipalloc.CustomIPAllocation")
}

func init() { proto.RegisterFile("ipalloc.proto", fileDescriptor_20954971669de07a) }

var fileDescriptor_20954971669de07a = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x19, 0x5b, 0x9c, 0xf6, 0x69, 0xb1, 0xbe, 0x55, 0x44, 0x84, 0x52, 0x37, 0xe3, 0xa6,
	0x0b, 0x3d, 0x41, 0x11, 0xc1, 0x6e, 0xa4, 0xcc, 0x05, 0x86, 0x98, 0x3c, 0x21, 0xd8, 0xe6, 0x3d,
	0x92, 0xa8, 0x97, 0xf0, 0x0c, 0x9e, 0x55, 0x26, 0xcd, 0x14, 0xc1, 0x5d, 0xfe, 0xef, 0x27, 0xe1,
	0xcb, 0x0f, 0x33, 0x27, 0x7a, 0xb7, 0x63, 0xb3, 0x92, 0xc0, 0x89, 0xb1, 0x2e, 0x71, 0xf9, 0x5d,
	0x01, 0x3e, 0x7e, 0xc4, 0xc4, 0xfb, 0x2d, 0xdb, 0x8d, 0x4f, 0x14, 0xde, 0xb4, 0x21, 0x44, 0x18,
	0x7b, 0xbd, 0x27, 0x55, 0x2d, 0xaa, 0x66, 0xda, 0xe6, 0x33, 0x2a, 0xa8, 0x3d, 0xa5, 0x2f, 0x0e,
	0xef, 0xea, 0x24, 0xe3, 0x21, 0xe2, 0x0d, 0x80, 0x93, 0x4e, 0x5b, 0x1b, 0x28, 0x46, 0x35, 0xca,
	0xe5, 0xd4, 0xc9, 0xfa, 0x00, 0xf0, 0x0e, 0xe6, 0x91, 0xc2, 0xa7, 0x33, 0xd4, 0x91, 0xb7, 0xc2,
	0xce, 0x27, 0x35, 0x5e, 0x54, 0xcd, 0xa4, 0xbd, 0x28, 0xfc, 0xa9, 0xe0, 0xe5, 0xcf, 0x51, 0x67,
	0xb3, 0x5d, 0xf7, 0x82, 0x3a, 0x39, 0xf6, 0x78, 0x05, 0x13, 0x61, 0xdb, 0xfd, 0x51, 0xaa, 0x85,
	0xed, 0x4b, 0x6f, 0x75, 0x0b, 0xb3, 0xa1, 0x8a, 0xa2, 0x0d, 0x15, 0xb7, 0xf3, 0xd2, 0x67, 0x86,
	0xcf, 0x70, 0x69, 0xf2, 0xab, 0x9d, 0x1b, 0xbe, 0xd8, 0x7b, 0x8e, 0x9a, 0xb3, 0xfb, 0xeb, 0xd5,
	0xb0, 0xcc, 0xff, 0x19, 0xda, 0xf9, 0xe1, 0xd6, 0x11, 0xc4, 0xd7, 0xd3, 0xbc, 0xdf, 0xc3, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x45, 0xdf, 0xe5, 0x50, 0x01, 0x00, 0x00,
}
