// Code generated by protoc-gen-go.
// source: namespace.proto
// DO NOT EDIT!

/*
Package namespace is a generated protocol buffer package.

Package namespace defines data model for Kubernetes Namespace.

It is generated from these files:
	namespace.proto

It has these top-level messages:
	Namespace
*/
package namespace

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// Namespace provides a scope for resource names.
type Namespace struct {
	// Name of the namespace.
	// Cannot be updated.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// A list of labels attached to this namespace.
	// +optional
	Label []*Namespace_Label `protobuf:"bytes,3,rep,name=label" json:"label,omitempty"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}

func (m *Namespace) GetLabel() []*Namespace_Label {
	if m != nil {
		return m.Label
	}
	return nil
}

// Label is a key/value pair attached to an object (namespace in this case).
// Labels are used to organize and to select subsets of objects.
type Namespace_Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Namespace_Label) Reset()         { *m = Namespace_Label{} }
func (m *Namespace_Label) String() string { return proto.CompactTextString(m) }
func (*Namespace_Label) ProtoMessage()    {}

func init() {
}
