// Code generated by protoc-gen-go. DO NOT EDIT.
// source: namespace.proto

/*
Package namespace is a generated protocol buffer package.

Package namespace defines data model for Kubernetes Namespace.

It is generated from these files:
	namespace.proto

It has these top-level messages:
	Namespace
*/
package namespace

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Namespace provides a scope for resource names.
type Namespace struct {
	// Name of the namespace.
	// Cannot be updated.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// A list of labels attached to this namespace.
	// +optional
	Label []*Namespace_Label `protobuf:"bytes,3,rep,name=label" json:"label,omitempty"`
}

func (m *Namespace) Reset()                    { *m = Namespace{} }
func (m *Namespace) String() string            { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()               {}
func (*Namespace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Namespace) GetLabel() []*Namespace_Label {
	if m != nil {
		return m.Label
	}
	return nil
}

// Label is a key/value pair attached to an object (namespace in this case).
// Labels are used to organize and to select subsets of objects.
type Namespace_Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Namespace_Label) Reset()                    { *m = Namespace_Label{} }
func (m *Namespace_Label) String() string            { return proto.CompactTextString(m) }
func (*Namespace_Label) ProtoMessage()               {}
func (*Namespace_Label) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Namespace_Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Namespace_Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Namespace)(nil), "namespace.Namespace")
	proto.RegisterType((*Namespace_Label)(nil), "namespace.Namespace.Label")
}

func init() { proto.RegisterFile("namespace.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x4b, 0xcc, 0x4d,
	0x2d, 0x2e, 0x48, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x35, 0x31, 0x72, 0x71, 0xfa, 0xc1, 0x78, 0x42, 0x42, 0x5c, 0x2c, 0x20, 0x29, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0xc8, 0x80, 0x8b, 0x35, 0x27, 0x31, 0x29, 0x35, 0x47, 0x82,
	0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x4a, 0x0f, 0x61, 0x1a, 0x5c, 0xa3, 0x9e, 0x0f, 0x48, 0x45,
	0x10, 0x44, 0xa1, 0x94, 0x3e, 0x17, 0x2b, 0x98, 0x2f, 0x24, 0xc0, 0xc5, 0x9c, 0x9d, 0x5a, 0x09,
	0x35, 0x0d, 0xc4, 0x14, 0x12, 0xe1, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x02, 0x8b,
	0x41, 0x38, 0x49, 0x6c, 0x60, 0x67, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x36, 0x65,
	0x3c, 0xa9, 0x00, 0x00, 0x00,
}
