#!/bin/bash

set -eo pipefail

export K8S_NODE_OS=${K8S_NODE_OS:-ubuntu}
export K8S_NODES=${K8S_NODES:-1}
export VAGRANT_DEFAULT_PROVIDER=${VAGRANT_DEFAULT_PROVIDER:-vmware_fusion}

# Default values for environment deploymen
DEV_ENV="false"
TEST_ENV="true"

# Override defaults from arguments
while [ "$1" != "" ]; do
    case $1 in
        -d | --dev-env )
            DEV_ENV="true"
            echo "Using development environment"
            ;;
        -t | --test-env )
            echo "Using testing environment"
            ;;
        * )
            echo "Invalid parameter: "$1
            exit 1
    esac
    shift
done

if [ "${DEV_ENV}" == "true" ]
then
    if [ "${VAGRANT_DEFAULT_PROVIDER}" == "vmware_fusion" ]
    then
        cp ../Vagrantfiles/vmware-dev ../Vagrantfile
        vagrant up
        exit 1
    else 
        cp ../Vagrantfiles/virtualbox-dev ../Vagrantfile
        vagrant up
        exit 1
    fi
fi
  
if [ "${VAGRANT_DEFAULT_PROVIDER}" == "vmware_fusion" ]
then
    cp ../Vagrantfiles/vmware-prod ../Vagrantfile
    vagrant up
else 
    cp ../Vagrantfiles/virtualbox-prod ../Vagrantfile
    vagrant up
fi
