// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	versioned "github.com/contiv/vpp/plugins/crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/contiv/vpp/plugins/crd/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/contiv/vpp/plugins/crd/pkg/client/listers/contivppio/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ServiceFunctionChainInformer provides access to a shared informer and lister for
// ServiceFunctionChains.
type ServiceFunctionChainInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ServiceFunctionChainLister
}

type serviceFunctionChainInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewServiceFunctionChainInformer constructs a new informer for ServiceFunctionChain type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewServiceFunctionChainInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredServiceFunctionChainInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredServiceFunctionChainInformer constructs a new informer for ServiceFunctionChain type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredServiceFunctionChainInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ContivppV1().ServiceFunctionChains(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ContivppV1().ServiceFunctionChains(namespace).Watch(options)
			},
		},
		&contivppiov1.ServiceFunctionChain{},
		resyncPeriod,
		indexers,
	)
}

func (f *serviceFunctionChainInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredServiceFunctionChainInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *serviceFunctionChainInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&contivppiov1.ServiceFunctionChain{}, f.defaultInformer)
}

func (f *serviceFunctionChainInformer) Lister() v1.ServiceFunctionChainLister {
	return v1.NewServiceFunctionChainLister(f.Informer().GetIndexer())
}
