// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	contivppiov1 "github.com/contiv/vpp/plugins/crd/pkg/apis/contivppio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomConfigurations implements CustomConfigurationInterface
type FakeCustomConfigurations struct {
	Fake *FakeContivppV1
	ns   string
}

var customconfigurationsResource = schema.GroupVersionResource{Group: "contivpp.io", Version: "v1", Resource: "customconfigurations"}

var customconfigurationsKind = schema.GroupVersionKind{Group: "contivpp.io", Version: "v1", Kind: "CustomConfiguration"}

// Get takes name of the customConfiguration, and returns the corresponding customConfiguration object, and an error if there is any.
func (c *FakeCustomConfigurations) Get(name string, options v1.GetOptions) (result *contivppiov1.CustomConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customconfigurationsResource, c.ns, name), &contivppiov1.CustomConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.CustomConfiguration), err
}

// List takes label and field selectors, and returns the list of CustomConfigurations that match those selectors.
func (c *FakeCustomConfigurations) List(opts v1.ListOptions) (result *contivppiov1.CustomConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customconfigurationsResource, customconfigurationsKind, c.ns, opts), &contivppiov1.CustomConfigurationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &contivppiov1.CustomConfigurationList{ListMeta: obj.(*contivppiov1.CustomConfigurationList).ListMeta}
	for _, item := range obj.(*contivppiov1.CustomConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customConfigurations.
func (c *FakeCustomConfigurations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a customConfiguration and creates it.  Returns the server's representation of the customConfiguration, and an error, if there is any.
func (c *FakeCustomConfigurations) Create(customConfiguration *contivppiov1.CustomConfiguration) (result *contivppiov1.CustomConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customconfigurationsResource, c.ns, customConfiguration), &contivppiov1.CustomConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.CustomConfiguration), err
}

// Update takes the representation of a customConfiguration and updates it. Returns the server's representation of the customConfiguration, and an error, if there is any.
func (c *FakeCustomConfigurations) Update(customConfiguration *contivppiov1.CustomConfiguration) (result *contivppiov1.CustomConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customconfigurationsResource, c.ns, customConfiguration), &contivppiov1.CustomConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.CustomConfiguration), err
}

// Delete takes name of the customConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeCustomConfigurations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customconfigurationsResource, c.ns, name), &contivppiov1.CustomConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomConfigurations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customconfigurationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &contivppiov1.CustomConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched customConfiguration.
func (c *FakeCustomConfigurations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *contivppiov1.CustomConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customconfigurationsResource, c.ns, name, pt, data, subresources...), &contivppiov1.CustomConfiguration{})

	if obj == nil {
		return nil, err
	}
	return obj.(*contivppiov1.CustomConfiguration), err
}
