apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        # ldpreload-related labels
        ldpreload: "true"
    spec:
      # optional - deploy on preferred node
#      nodeSelector:
#        kubernetes.io/hostname: ubuntu
      containers:
        - name: server
          imagePullPolicy: IfNotPresent
          image: nginx
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          env:
            # ldpreload-related env vars
            - name: VCL_APP_SCOPE_GLOBAL
              value: ""
            # enable verbose VCL debugs, do not use for production
            - name: VCL_DEBUG
              value: "3"
