// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ksr_nb_api.proto

// Package ksrapi defines the data model for KSR plugin's northbound API.

package ksrapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// KsrStats holds statistics for an individual KSR type
type KsrStats struct {
	// Number of add operations.
	Adds uint64 `protobuf:"varint,1,opt,name=Adds,proto3" json:"Adds,omitempty"`
	// Number of delete operations.
	Updates uint64 `protobuf:"varint,2,opt,name=Updates,proto3" json:"Updates,omitempty"`
	// Number of delete operations.
	Deletes uint64 `protobuf:"varint,3,opt,name=Deletes,proto3" json:"Deletes,omitempty"`
	// Number of data store resync runs.
	Resyncs uint64 `protobuf:"varint,4,opt,name=Resyncs,proto3" json:"Resyncs,omitempty"`
	// Number of add operation errors.
	AddErrors uint64 `protobuf:"varint,5,opt,name=AddErrors,proto3" json:"AddErrors,omitempty"`
	// Number of delete operation errors.
	UpdErrors uint64 `protobuf:"varint,6,opt,name=UpdErrors,proto3" json:"UpdErrors,omitempty"`
	// Number of delete operation errors.
	DelErrors uint64 `protobuf:"varint,7,opt,name=DelErrors,proto3" json:"DelErrors,omitempty"`
	// Number of operations where one or more arguments were invalid.
	ArgErrors uint64 `protobuf:"varint,8,opt,name=ArgErrors,proto3" json:"ArgErrors,omitempty"`
	// Number of of data store resync errors.
	ResErrors            uint64   `protobuf:"varint,9,opt,name=ResErrors,proto3" json:"ResErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KsrStats) Reset()         { *m = KsrStats{} }
func (m *KsrStats) String() string { return proto.CompactTextString(m) }
func (*KsrStats) ProtoMessage()    {}
func (*KsrStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_53ba764e9d53bcd7, []int{0}
}

func (m *KsrStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KsrStats.Unmarshal(m, b)
}
func (m *KsrStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KsrStats.Marshal(b, m, deterministic)
}
func (m *KsrStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KsrStats.Merge(m, src)
}
func (m *KsrStats) XXX_Size() int {
	return xxx_messageInfo_KsrStats.Size(m)
}
func (m *KsrStats) XXX_DiscardUnknown() {
	xxx_messageInfo_KsrStats.DiscardUnknown(m)
}

var xxx_messageInfo_KsrStats proto.InternalMessageInfo

func (m *KsrStats) GetAdds() uint64 {
	if m != nil {
		return m.Adds
	}
	return 0
}

func (m *KsrStats) GetUpdates() uint64 {
	if m != nil {
		return m.Updates
	}
	return 0
}

func (m *KsrStats) GetDeletes() uint64 {
	if m != nil {
		return m.Deletes
	}
	return 0
}

func (m *KsrStats) GetResyncs() uint64 {
	if m != nil {
		return m.Resyncs
	}
	return 0
}

func (m *KsrStats) GetAddErrors() uint64 {
	if m != nil {
		return m.AddErrors
	}
	return 0
}

func (m *KsrStats) GetUpdErrors() uint64 {
	if m != nil {
		return m.UpdErrors
	}
	return 0
}

func (m *KsrStats) GetDelErrors() uint64 {
	if m != nil {
		return m.DelErrors
	}
	return 0
}

func (m *KsrStats) GetArgErrors() uint64 {
	if m != nil {
		return m.ArgErrors
	}
	return 0
}

func (m *KsrStats) GetResErrors() uint64 {
	if m != nil {
		return m.ResErrors
	}
	return 0
}

// Stats holds aggregated statistics for all KSR types in the KSR process.
type Stats struct {
	// Statistics for the Namespace Reflector
	NamespaceStats *KsrStats `protobuf:"bytes,1,opt,name=namespaceStats,proto3" json:"namespaceStats,omitempty"`
	// Statistics for the Pod Reflector
	PodStats *KsrStats `protobuf:"bytes,2,opt,name=podStats,proto3" json:"podStats,omitempty"`
	// Statistics for the Network Policy Reflector
	PolicyStats *KsrStats `protobuf:"bytes,3,opt,name=policyStats,proto3" json:"policyStats,omitempty"`
	// Statistics for the Endpoints Reflector
	EndpointsStats *KsrStats `protobuf:"bytes,4,opt,name=endpointsStats,proto3" json:"endpointsStats,omitempty"`
	// Statistics for the Service Reflector
	ServiceStats *KsrStats `protobuf:"bytes,5,opt,name=serviceStats,proto3" json:"serviceStats,omitempty"`
	// Statistics for the Node Reflector
	NodeStats *KsrStats `protobuf:"bytes,6,opt,name=nodeStats,proto3" json:"nodeStats,omitempty"`
	// Statistics for the SfcPod Reflector
	SfcPodStats          *KsrStats `protobuf:"bytes,7,opt,name=sfcPodStats,proto3" json:"sfcPodStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Stats) Reset()         { *m = Stats{} }
func (m *Stats) String() string { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()    {}
func (*Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_53ba764e9d53bcd7, []int{1}
}

func (m *Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stats.Unmarshal(m, b)
}
func (m *Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stats.Marshal(b, m, deterministic)
}
func (m *Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stats.Merge(m, src)
}
func (m *Stats) XXX_Size() int {
	return xxx_messageInfo_Stats.Size(m)
}
func (m *Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Stats proto.InternalMessageInfo

func (m *Stats) GetNamespaceStats() *KsrStats {
	if m != nil {
		return m.NamespaceStats
	}
	return nil
}

func (m *Stats) GetPodStats() *KsrStats {
	if m != nil {
		return m.PodStats
	}
	return nil
}

func (m *Stats) GetPolicyStats() *KsrStats {
	if m != nil {
		return m.PolicyStats
	}
	return nil
}

func (m *Stats) GetEndpointsStats() *KsrStats {
	if m != nil {
		return m.EndpointsStats
	}
	return nil
}

func (m *Stats) GetServiceStats() *KsrStats {
	if m != nil {
		return m.ServiceStats
	}
	return nil
}

func (m *Stats) GetNodeStats() *KsrStats {
	if m != nil {
		return m.NodeStats
	}
	return nil
}

func (m *Stats) GetSfcPodStats() *KsrStats {
	if m != nil {
		return m.SfcPodStats
	}
	return nil
}

func init() {
	proto.RegisterType((*KsrStats)(nil), "ksrapi.KsrStats")
	proto.RegisterType((*Stats)(nil), "ksrapi.Stats")
}

func init() { proto.RegisterFile("ksr_nb_api.proto", fileDescriptor_53ba764e9d53bcd7) }

var fileDescriptor_53ba764e9d53bcd7 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbb, 0x6b, 0xf3, 0x30,
	0x14, 0xc5, 0x89, 0xe3, 0xe7, 0xcd, 0xc7, 0x47, 0xd0, 0xe4, 0xa1, 0x43, 0xc9, 0xd4, 0xa1, 0x78,
	0x48, 0x3b, 0x74, 0x0d, 0xa4, 0x53, 0x97, 0xe2, 0x92, 0x39, 0x28, 0x96, 0x5a, 0x4c, 0x5c, 0x49,
	0xe8, 0x9a, 0x42, 0xd6, 0xfe, 0xd3, 0x5d, 0x8b, 0x5e, 0x4e, 0x52, 0xd0, 0xe6, 0x7b, 0x7e, 0xe7,
	0x88, 0x7b, 0x0f, 0x86, 0xe5, 0x11, 0xf5, 0x5e, 0x1c, 0xf6, 0x54, 0xf5, 0x8d, 0xd2, 0x72, 0x94,
	0x24, 0x3f, 0xa2, 0xa6, 0xaa, 0x5f, 0x7d, 0x27, 0x50, 0xbe, 0xa0, 0x7e, 0x1b, 0xe9, 0x88, 0x84,
	0x40, 0xba, 0x61, 0x0c, 0xeb, 0xd9, 0xed, 0xec, 0x2e, 0x6d, 0xed, 0x37, 0xa9, 0xa1, 0xd8, 0x29,
	0x46, 0x47, 0x8e, 0x75, 0x62, 0xe5, 0x30, 0x1a, 0xb2, 0xe5, 0x03, 0x37, 0x64, 0xee, 0x88, 0x1f,
	0x0d, 0x69, 0x39, 0x9e, 0x44, 0x87, 0x75, 0xea, 0x88, 0x1f, 0xc9, 0x0d, 0x54, 0x1b, 0xc6, 0x9e,
	0xb5, 0x96, 0x1a, 0xeb, 0xcc, 0xb2, 0xb3, 0x60, 0xe8, 0x4e, 0x05, 0x9a, 0x3b, 0x3a, 0x09, 0x86,
	0x6e, 0xf9, 0xe0, 0x69, 0xe1, 0xe8, 0x24, 0xd8, 0x97, 0xf5, 0x87, 0xa7, 0xa5, 0x7f, 0x39, 0x08,
	0x86, 0xb6, 0x1c, 0x3d, 0xad, 0x1c, 0x9d, 0x84, 0xd5, 0x4f, 0x02, 0x99, 0x6b, 0xe0, 0x09, 0xfe,
	0x0b, 0xfa, 0xc9, 0x51, 0xd1, 0x8e, 0x5b, 0xc5, 0x76, 0xb1, 0x58, 0x2f, 0x1b, 0xd7, 0x57, 0x13,
	0xba, 0x6a, 0xff, 0xf8, 0xc8, 0x3d, 0x94, 0x4a, 0x32, 0x97, 0x49, 0x22, 0x99, 0xc9, 0x41, 0xd6,
	0xb0, 0x50, 0x72, 0xe8, 0xbb, 0x93, 0x0b, 0xcc, 0x23, 0x81, 0x4b, 0x93, 0xd9, 0x8d, 0x0b, 0xa6,
	0x64, 0x2f, 0x46, 0x74, 0xb1, 0x34, 0xb6, 0xdb, 0xb5, 0x8f, 0x3c, 0xc2, 0x3f, 0xe4, 0xfa, 0xab,
	0x0f, 0x37, 0x65, 0x91, 0xdc, 0x95, 0x8b, 0x34, 0x50, 0x09, 0xc9, 0x7c, 0x24, 0x8f, 0x44, 0xce,
	0x16, 0x73, 0x13, 0xbe, 0x77, 0xaf, 0xa1, 0x84, 0x22, 0x76, 0xd3, 0x85, 0xe9, 0x90, 0xdb, 0xbf,
	0xf1, 0xe1, 0x37, 0x00, 0x00, 0xff, 0xff, 0x74, 0xed, 0x01, 0xc5, 0xa1, 0x02, 0x00, 0x00,
}
