---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-agent-cfg
data:
  etcd.conf: |
    insecure-transport: false
    ca-file: /var/contiv/etcd-secrets/ca.pem
    cert-file: /var/contiv/etcd-secrets/client.pem
    key-file: /var/contiv/etcd-secrets/client-key.pem
    dial-timeout: 10000000000
    allow-delayed-start: true
    endpoints:
      - "147.75.98.202:32379"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vnf-vpp-cfg
data:
  vpp.conf: |
    unix {
      nodaemon
      cli-listen 0.0.0.0:5002
      cli-no-pager
      log /tmp/vpp.log
      full-coredump
    }
    plugins {
      plugin dpdk_plugin.so {
        disable
      }
    }
    api-trace {
      on
    }
    socksvr {
      default
    }
    statseg {
      default
    }
    nat {
      endpoint-dependent
      translation hash buckets 1048576
      translation hash memory 268435456
      user hash buckets 1024
      max translations per user 10000
    }

---
