// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cni.proto

package cni

/*
Package cni provides remote CNI functionality over gRPC. It follows
the CNI specification at https://github.com/containernetworking/cni/blob/master/SPEC.md
*/

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CNIReply_Interface_IP_Version int32

const (
	CNIReply_Interface_IP_IPV4 CNIReply_Interface_IP_Version = 0
	CNIReply_Interface_IP_IPV6 CNIReply_Interface_IP_Version = 1
)

var CNIReply_Interface_IP_Version_name = map[int32]string{
	0: "IPV4",
	1: "IPV6",
}
var CNIReply_Interface_IP_Version_value = map[string]int32{
	"IPV4": 0,
	"IPV6": 1,
}

func (x CNIReply_Interface_IP_Version) String() string {
	return proto.EnumName(CNIReply_Interface_IP_Version_name, int32(x))
}
func (CNIReply_Interface_IP_Version) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{1, 0, 0, 0}
}

// The request to add a container to network. Corresponds to the CNI specification
// at https://github.com/containernetworking/cni/blob/master/SPEC.md#parameters
type CNIRequest struct {
	// The version of CNI spec that the caller is using (container management system or the invoking plugin).
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Container ID unique across an administrative domain while the container is live.
	ContainerId string `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Path to the network namespace to be added, i.e. /proc/[pid]/ns/net or a bind-mount/link to it.
	NetworkNamespace string `protobuf:"bytes,3,opt,name=network_namespace,json=networkNamespace,proto3" json:"network_namespace,omitempty"`
	// Name of the interface inside the container. This is the name that should be assigned to the interface created inside the container (network namespace); consequently it must comply with the standard Linux restrictions on interface names.
	InterfaceName string `protobuf:"bytes,4,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// Network configuration. This is a JSON document describing a network to which a container can be joined. Optional.
	ExtraNwConfig string `protobuf:"bytes,5,opt,name=extra_nw_config,json=extraNwConfig,proto3" json:"extra_nw_config,omitempty"`
	// Extra arguments passed to CNI plugin. Optional.
	ExtraArguments string `protobuf:"bytes,6,opt,name=extra_arguments,json=extraArguments,proto3" json:"extra_arguments,omitempty"`
	// IPAM plugin configured for the CNI (empty for Contiv-internal IPAM).
	IpamPlugin string `protobuf:"bytes,7,opt,name=ipam_plugin,json=ipamPlugin,proto3" json:"ipam_plugin,omitempty"`
	// result of the IPAM plugin if it was configured for the CNI (empty for Contiv-internal IPAM).
	IpamResult           string   `protobuf:"bytes,8,opt,name=ipam_result,json=ipamResult,proto3" json:"ipam_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNIRequest) Reset()         { *m = CNIRequest{} }
func (m *CNIRequest) String() string { return proto.CompactTextString(m) }
func (*CNIRequest) ProtoMessage()    {}
func (*CNIRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{0}
}
func (m *CNIRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIRequest.Unmarshal(m, b)
}
func (m *CNIRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIRequest.Marshal(b, m, deterministic)
}
func (dst *CNIRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIRequest.Merge(dst, src)
}
func (m *CNIRequest) XXX_Size() int {
	return xxx_messageInfo_CNIRequest.Size(m)
}
func (m *CNIRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CNIRequest proto.InternalMessageInfo

func (m *CNIRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CNIRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *CNIRequest) GetNetworkNamespace() string {
	if m != nil {
		return m.NetworkNamespace
	}
	return ""
}

func (m *CNIRequest) GetInterfaceName() string {
	if m != nil {
		return m.InterfaceName
	}
	return ""
}

func (m *CNIRequest) GetExtraNwConfig() string {
	if m != nil {
		return m.ExtraNwConfig
	}
	return ""
}

func (m *CNIRequest) GetExtraArguments() string {
	if m != nil {
		return m.ExtraArguments
	}
	return ""
}

func (m *CNIRequest) GetIpamPlugin() string {
	if m != nil {
		return m.IpamPlugin
	}
	return ""
}

func (m *CNIRequest) GetIpamResult() string {
	if m != nil {
		return m.IpamResult
	}
	return ""
}

// The response to the CNIRequest. Corresponds to the CNI specification
// at https://github.com/containernetworking/cni/blob/master/SPEC.md#parameters
type CNIReply struct {
	// Result code. 0 = success, non-zero = error.
	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	// Error string in case that result != 0.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// List of interfaces connected to the container.
	Interfaces []*CNIReply_Interface `protobuf:"bytes,4,rep,name=interfaces" json:"interfaces,omitempty"`
	// List of routes configured in the container.
	Routes []*CNIReply_Route `protobuf:"bytes,5,rep,name=routes" json:"routes,omitempty"`
	// DNS entries. Repeated only because it is optional, normally there should be only one dns member.
	Dns                  []*CNIReply_DNS `protobuf:"bytes,6,rep,name=dns" json:"dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CNIReply) Reset()         { *m = CNIReply{} }
func (m *CNIReply) String() string { return proto.CompactTextString(m) }
func (*CNIReply) ProtoMessage()    {}
func (*CNIReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{1}
}
func (m *CNIReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIReply.Unmarshal(m, b)
}
func (m *CNIReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIReply.Marshal(b, m, deterministic)
}
func (dst *CNIReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIReply.Merge(dst, src)
}
func (m *CNIReply) XXX_Size() int {
	return xxx_messageInfo_CNIReply.Size(m)
}
func (m *CNIReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIReply.DiscardUnknown(m)
}

var xxx_messageInfo_CNIReply proto.InternalMessageInfo

func (m *CNIReply) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *CNIReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CNIReply) GetInterfaces() []*CNIReply_Interface {
	if m != nil {
		return m.Interfaces
	}
	return nil
}

func (m *CNIReply) GetRoutes() []*CNIReply_Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *CNIReply) GetDns() []*CNIReply_DNS {
	if m != nil {
		return m.Dns
	}
	return nil
}

// Interface details, as described in https://github.com/containernetworking/cni/blob/master/SPEC.md#result
type CNIReply_Interface struct {
	// Name if the interface.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MAC address of the interface.
	Mac string `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	// Details about the sandbox (if any) the interface is in. Can be a netns path, empty/omitted for host interfaces.
	Sandbox string `protobuf:"bytes,3,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	// List of IP addresses applied on the interface.
	IpAddresses          []*CNIReply_Interface_IP `protobuf:"bytes,4,rep,name=ip_addresses,json=ipAddresses" json:"ip_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CNIReply_Interface) Reset()         { *m = CNIReply_Interface{} }
func (m *CNIReply_Interface) String() string { return proto.CompactTextString(m) }
func (*CNIReply_Interface) ProtoMessage()    {}
func (*CNIReply_Interface) Descriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{1, 0}
}
func (m *CNIReply_Interface) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIReply_Interface.Unmarshal(m, b)
}
func (m *CNIReply_Interface) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIReply_Interface.Marshal(b, m, deterministic)
}
func (dst *CNIReply_Interface) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIReply_Interface.Merge(dst, src)
}
func (m *CNIReply_Interface) XXX_Size() int {
	return xxx_messageInfo_CNIReply_Interface.Size(m)
}
func (m *CNIReply_Interface) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIReply_Interface.DiscardUnknown(m)
}

var xxx_messageInfo_CNIReply_Interface proto.InternalMessageInfo

func (m *CNIReply_Interface) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CNIReply_Interface) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *CNIReply_Interface) GetSandbox() string {
	if m != nil {
		return m.Sandbox
	}
	return ""
}

func (m *CNIReply_Interface) GetIpAddresses() []*CNIReply_Interface_IP {
	if m != nil {
		return m.IpAddresses
	}
	return nil
}

// IP address details, as described in https://github.com/containernetworking/cni/blob/master/SPEC.md#ips
type CNIReply_Interface_IP struct {
	// IP version.
	Version CNIReply_Interface_IP_Version `protobuf:"varint,1,opt,name=version,proto3,enum=cni.CNIReply_Interface_IP_Version" json:"version,omitempty"`
	// IP address in CIDR notation (eg "192.168.1.3/24").
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// The default gateway for this subnet, if one exists.
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNIReply_Interface_IP) Reset()         { *m = CNIReply_Interface_IP{} }
func (m *CNIReply_Interface_IP) String() string { return proto.CompactTextString(m) }
func (*CNIReply_Interface_IP) ProtoMessage()    {}
func (*CNIReply_Interface_IP) Descriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{1, 0, 0}
}
func (m *CNIReply_Interface_IP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIReply_Interface_IP.Unmarshal(m, b)
}
func (m *CNIReply_Interface_IP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIReply_Interface_IP.Marshal(b, m, deterministic)
}
func (dst *CNIReply_Interface_IP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIReply_Interface_IP.Merge(dst, src)
}
func (m *CNIReply_Interface_IP) XXX_Size() int {
	return xxx_messageInfo_CNIReply_Interface_IP.Size(m)
}
func (m *CNIReply_Interface_IP) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIReply_Interface_IP.DiscardUnknown(m)
}

var xxx_messageInfo_CNIReply_Interface_IP proto.InternalMessageInfo

func (m *CNIReply_Interface_IP) GetVersion() CNIReply_Interface_IP_Version {
	if m != nil {
		return m.Version
	}
	return CNIReply_Interface_IP_IPV4
}

func (m *CNIReply_Interface_IP) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CNIReply_Interface_IP) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

// Route details, as described in https://github.com/containernetworking/cni/blob/master/SPEC.md#routes
type CNIReply_Route struct {
	// Destination subnet specified in CIDR notation.
	Dst string `protobuf:"bytes,1,opt,name=dst,proto3" json:"dst,omitempty"`
	// IP of the gateway. If omitted, a default gateway is assumed.
	Gw                   string   `protobuf:"bytes,2,opt,name=gw,proto3" json:"gw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNIReply_Route) Reset()         { *m = CNIReply_Route{} }
func (m *CNIReply_Route) String() string { return proto.CompactTextString(m) }
func (*CNIReply_Route) ProtoMessage()    {}
func (*CNIReply_Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{1, 1}
}
func (m *CNIReply_Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIReply_Route.Unmarshal(m, b)
}
func (m *CNIReply_Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIReply_Route.Marshal(b, m, deterministic)
}
func (dst *CNIReply_Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIReply_Route.Merge(dst, src)
}
func (m *CNIReply_Route) XXX_Size() int {
	return xxx_messageInfo_CNIReply_Route.Size(m)
}
func (m *CNIReply_Route) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIReply_Route.DiscardUnknown(m)
}

var xxx_messageInfo_CNIReply_Route proto.InternalMessageInfo

func (m *CNIReply_Route) GetDst() string {
	if m != nil {
		return m.Dst
	}
	return ""
}

func (m *CNIReply_Route) GetGw() string {
	if m != nil {
		return m.Gw
	}
	return ""
}

// DNS details, as described in https://github.com/containernetworking/cni/blob/master/SPEC.md#dns
type CNIReply_DNS struct {
	// The local domain used for short hostname lookups.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// List of a priority-ordered list of DNS nameservers that this network is aware of.
	Nameservers []string `protobuf:"bytes,2,rep,name=nameservers" json:"nameservers,omitempty"`
	// List of priority ordered search domains for short hostname lookups. Will be preferred over domain by most resolvers.
	Search []string `protobuf:"bytes,3,rep,name=search" json:"search,omitempty"`
	// Listt of options that can be passed to the resolver.
	Options              []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CNIReply_DNS) Reset()         { *m = CNIReply_DNS{} }
func (m *CNIReply_DNS) String() string { return proto.CompactTextString(m) }
func (*CNIReply_DNS) ProtoMessage()    {}
func (*CNIReply_DNS) Descriptor() ([]byte, []int) {
	return fileDescriptor_cni_55b0927b6e753cb6, []int{1, 2}
}
func (m *CNIReply_DNS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CNIReply_DNS.Unmarshal(m, b)
}
func (m *CNIReply_DNS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CNIReply_DNS.Marshal(b, m, deterministic)
}
func (dst *CNIReply_DNS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CNIReply_DNS.Merge(dst, src)
}
func (m *CNIReply_DNS) XXX_Size() int {
	return xxx_messageInfo_CNIReply_DNS.Size(m)
}
func (m *CNIReply_DNS) XXX_DiscardUnknown() {
	xxx_messageInfo_CNIReply_DNS.DiscardUnknown(m)
}

var xxx_messageInfo_CNIReply_DNS proto.InternalMessageInfo

func (m *CNIReply_DNS) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *CNIReply_DNS) GetNameservers() []string {
	if m != nil {
		return m.Nameservers
	}
	return nil
}

func (m *CNIReply_DNS) GetSearch() []string {
	if m != nil {
		return m.Search
	}
	return nil
}

func (m *CNIReply_DNS) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*CNIRequest)(nil), "cni.CNIRequest")
	proto.RegisterType((*CNIReply)(nil), "cni.CNIReply")
	proto.RegisterType((*CNIReply_Interface)(nil), "cni.CNIReply.Interface")
	proto.RegisterType((*CNIReply_Interface_IP)(nil), "cni.CNIReply.Interface.IP")
	proto.RegisterType((*CNIReply_Route)(nil), "cni.CNIReply.Route")
	proto.RegisterType((*CNIReply_DNS)(nil), "cni.CNIReply.DNS")
	proto.RegisterEnum("cni.CNIReply_Interface_IP_Version", CNIReply_Interface_IP_Version_name, CNIReply_Interface_IP_Version_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RemoteCNI service

type RemoteCNIClient interface {
	// The request to add a container to network.
	Add(ctx context.Context, in *CNIRequest, opts ...grpc.CallOption) (*CNIReply, error)
	// The request to delete a container from network.
	Delete(ctx context.Context, in *CNIRequest, opts ...grpc.CallOption) (*CNIReply, error)
}

type remoteCNIClient struct {
	cc *grpc.ClientConn
}

func NewRemoteCNIClient(cc *grpc.ClientConn) RemoteCNIClient {
	return &remoteCNIClient{cc}
}

func (c *remoteCNIClient) Add(ctx context.Context, in *CNIRequest, opts ...grpc.CallOption) (*CNIReply, error) {
	out := new(CNIReply)
	err := c.cc.Invoke(ctx, "/cni.RemoteCNI/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteCNIClient) Delete(ctx context.Context, in *CNIRequest, opts ...grpc.CallOption) (*CNIReply, error) {
	out := new(CNIReply)
	err := c.cc.Invoke(ctx, "/cni.RemoteCNI/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RemoteCNI service

type RemoteCNIServer interface {
	// The request to add a container to network.
	Add(context.Context, *CNIRequest) (*CNIReply, error)
	// The request to delete a container from network.
	Delete(context.Context, *CNIRequest) (*CNIReply, error)
}

func RegisterRemoteCNIServer(s *grpc.Server, srv RemoteCNIServer) {
	s.RegisterService(&_RemoteCNI_serviceDesc, srv)
}

func _RemoteCNI_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CNIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCNIServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cni.RemoteCNI/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCNIServer).Add(ctx, req.(*CNIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteCNI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CNIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCNIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cni.RemoteCNI/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCNIServer).Delete(ctx, req.(*CNIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteCNI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cni.RemoteCNI",
	HandlerType: (*RemoteCNIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _RemoteCNI_Add_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RemoteCNI_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cni.proto",
}

func init() { proto.RegisterFile("cni.proto", fileDescriptor_cni_55b0927b6e753cb6) }

var fileDescriptor_cni_55b0927b6e753cb6 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x4f, 0x6e, 0x13, 0x31,
	0x14, 0xc6, 0x9b, 0x99, 0xfc, 0x69, 0x5e, 0xda, 0x34, 0x7d, 0x20, 0xb0, 0x22, 0x21, 0x42, 0x10,
	0xb4, 0x50, 0x29, 0x8b, 0x82, 0x60, 0x03, 0x8b, 0xaa, 0xdd, 0xcc, 0x26, 0x8a, 0xa6, 0x52, 0xb7,
	0xc1, 0x9d, 0x71, 0x83, 0x45, 0xc6, 0x9e, 0xda, 0x0e, 0xd3, 0x5e, 0x80, 0x1b, 0x70, 0x01, 0x4e,
	0xc0, 0x11, 0x91, 0x1d, 0x7b, 0xd2, 0x2c, 0x2a, 0x76, 0xfe, 0xbe, 0xf7, 0xb3, 0xc7, 0xef, 0xb3,
	0x3d, 0xd0, 0xcd, 0x04, 0x9f, 0x94, 0x4a, 0x1a, 0x89, 0x71, 0x26, 0xf8, 0xf8, 0x6f, 0x04, 0x70,
	0x3e, 0x4d, 0x52, 0x76, 0xbb, 0x62, 0xda, 0x20, 0x81, 0xce, 0x4f, 0xa6, 0x34, 0x97, 0x82, 0x34,
	0x46, 0x8d, 0xe3, 0x6e, 0x1a, 0x24, 0xbe, 0x82, 0xbd, 0x4c, 0x0a, 0x43, 0xb9, 0x60, 0x6a, 0xce,
	0x73, 0x12, 0xb9, 0x72, 0xaf, 0xf6, 0x92, 0x1c, 0x4f, 0xe0, 0x50, 0x30, 0x53, 0x49, 0xf5, 0x63,
	0x2e, 0x68, 0xc1, 0x74, 0x49, 0x33, 0x46, 0x62, 0xc7, 0x0d, 0x7c, 0x61, 0x1a, 0x7c, 0x7c, 0x03,
	0x7d, 0x2e, 0x0c, 0x53, 0x37, 0x34, 0x63, 0x0e, 0x27, 0x4d, 0x47, 0xee, 0xd7, 0xae, 0x65, 0xf1,
	0x2d, 0x1c, 0xb0, 0x3b, 0xa3, 0xe8, 0x5c, 0x54, 0xf3, 0x4c, 0x8a, 0x1b, 0xbe, 0x20, 0xad, 0x35,
	0xe7, 0xec, 0x69, 0x75, 0xee, 0x4c, 0x3c, 0x0a, 0x1c, 0x55, 0x8b, 0x55, 0xc1, 0x84, 0xd1, 0xa4,
	0xed, 0xb8, 0xbe, 0xb3, 0xcf, 0x82, 0x8b, 0x2f, 0xa1, 0xc7, 0x4b, 0x5a, 0xcc, 0xcb, 0xe5, 0x6a,
	0xc1, 0x05, 0xe9, 0x38, 0x08, 0xac, 0x35, 0x73, 0x4e, 0x0d, 0x28, 0xa6, 0x57, 0x4b, 0x43, 0x76,
	0x37, 0x40, 0xea, 0x9c, 0xf1, 0xaf, 0x16, 0xec, 0xba, 0xc8, 0xca, 0xe5, 0x3d, 0x3e, 0x83, 0xb6,
	0x07, 0x6d, 0x5e, 0xfb, 0xa9, 0x57, 0xf8, 0x14, 0x5a, 0x4c, 0x29, 0xa9, 0x7c, 0x4e, 0x6b, 0x81,
	0x9f, 0x01, 0xea, 0xf6, 0x34, 0x69, 0x8e, 0xe2, 0xe3, 0xde, 0xe9, 0xf3, 0x89, 0x3d, 0x92, 0xb0,
	0xe0, 0x24, 0x09, 0xf5, 0xf4, 0x01, 0x8a, 0x27, 0xd0, 0x56, 0x72, 0x65, 0x98, 0x26, 0x2d, 0x37,
	0xe9, 0xc9, 0xf6, 0xa4, 0xd4, 0xd6, 0x52, 0x8f, 0xe0, 0x6b, 0x88, 0x73, 0x61, 0xfb, 0xb7, 0xe4,
	0xe1, 0x36, 0x79, 0x31, 0xbd, 0x4c, 0x6d, 0x75, 0xf8, 0x27, 0x82, 0x6e, 0xfd, 0x2d, 0x44, 0x68,
	0xba, 0x33, 0x58, 0x1f, 0xba, 0x1b, 0xe3, 0x00, 0xe2, 0x82, 0x66, 0xbe, 0x01, 0x3b, 0xb4, 0xb7,
	0x43, 0x53, 0x91, 0x5f, 0xcb, 0x3b, 0x7f, 0xac, 0x41, 0xe2, 0x57, 0xd8, 0xe3, 0xe5, 0x9c, 0xe6,
	0xb9, 0x62, 0x5a, 0xd7, 0xad, 0x0d, 0x1f, 0x69, 0x6d, 0x92, 0xcc, 0xd2, 0x1e, 0x2f, 0xcf, 0x02,
	0x3e, 0xfc, 0xdd, 0x80, 0x28, 0x99, 0xe1, 0x97, 0xed, 0xdb, 0xd7, 0x3f, 0x1d, 0x3f, 0xbe, 0xc0,
	0xe4, 0x6a, 0x4d, 0x6e, 0x6e, 0x28, 0x81, 0x8e, 0xdf, 0x80, 0xdf, 0x73, 0x90, 0xb6, 0xb2, 0xa0,
	0x86, 0x55, 0xf4, 0x3e, 0xec, 0xdb, 0xcb, 0xf1, 0x0b, 0xe8, 0xf8, 0x75, 0x70, 0x17, 0x9a, 0xc9,
	0xec, 0xea, 0xe3, 0x60, 0xc7, 0x8f, 0x3e, 0x0d, 0x1a, 0xc3, 0x77, 0xd0, 0x72, 0xd1, 0xda, 0x2c,
	0x72, 0x6d, 0x7c, 0x3c, 0x76, 0x88, 0x7d, 0x88, 0x16, 0x95, 0xff, 0x50, 0xb4, 0xa8, 0x86, 0xb7,
	0x10, 0x5f, 0x4c, 0x2f, 0xed, 0x7d, 0xc8, 0x65, 0x41, 0x79, 0x78, 0x3f, 0x5e, 0xe1, 0x08, 0x7a,
	0xee, 0x4d, 0x30, 0x65, 0xb7, 0x4b, 0xa2, 0x51, 0x6c, 0x5f, 0xcf, 0x03, 0xcb, 0xce, 0xd4, 0x8c,
	0xaa, 0xec, 0x3b, 0x89, 0x5d, 0xd1, 0x2b, 0xbb, 0x79, 0x59, 0x1a, 0x2e, 0xc5, 0x3a, 0xd5, 0x6e,
	0x1a, 0xe4, 0xe9, 0x37, 0xe8, 0xa6, 0xac, 0x90, 0x86, 0x9d, 0x4f, 0x13, 0x3c, 0x82, 0xf8, 0x2c,
	0xcf, 0xf1, 0x60, 0x93, 0x98, 0x7b, 0xd1, 0xc3, 0xfd, 0xad, 0x08, 0xc7, 0x3b, 0xf8, 0x1e, 0xda,
	0x17, 0x6c, 0xc9, 0x0c, 0xfb, 0x3f, 0x7b, 0xdd, 0x76, 0x7f, 0x8a, 0x0f, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xde, 0x06, 0xc1, 0x66, 0x36, 0x04, 0x00, 0x00,
}
