#!/bin/bash

# Find the most recent container running vpp, and execute the vpp cli that resides within.

set -euo pipefail

get_vswitch_container_id() {
    # There may be more than one vswitch container if an upgrade/redeploy is
    # happening, so go for the newest one.
    docker ps --format '{{.CreatedAt}} {{.Image}} {{.ID}}' | grep -E " $1@?[^ ]* [^ ]+$" | sort -nr | \
        head -n 1 | sed -e 's|.* ||g'
}

IMAGE="contivvpp/vswitch"

# Test and see if we need more access.
if ! docker info >/dev/null 2>&1
then
    echo "Error connecting to the Docker daemon.  Please try rerunning with sudo." >&2
    exit 1
fi

# In K8s 1.10 and above only Image IDs are displayed by 'docker ps' instead of Image
# names. If we can't get the vswitch container by its image name, exclude pause containers
# and lookup a container with name containing 'contiv-switch'.
if ! ID=$(get_vswitch_container_id "$IMAGE") || [ -z "$ID" ]
then
    if ! ID=$(docker ps --format '{{.CreatedAt}}|{{.ID}}|{{.Names}}'| grep -a contiv-vswitch | grep -a -v pause | sort -nr | head -n 1 | cut -f 2 -d '|') || [ -z "$ID" ]
    then
        echo "Error finding a $IMAGE image." >&2
        exit 1
    fi
fi

DOCKER_ARGS=
if [ -t 0 ]
then
    DOCKER_ARGS="-t"
fi

# Docker args can't be quoted here because otherwise when there are no args, docker would get an argument that is an
# empty string (causing it to error), instead of no arg at all.
exec docker exec -i $DOCKER_ARGS "$ID" /usr/bin/vppctl "$@"
